
== Grundlegende Moves

Dieses Kapitel enthält Moves, die allen Charakteren zur Verfügung stehen.
Sie lassen sich in zwei Kategorien unterteilen: Grundlegende und spezielle.

Grundlegende Moves machen den Löwenanteil des Abenteurerlebens aus.
Sie kommen zur Anwendung in Kämpfen, angespannten Verhandlungen, gefährlichen Gegenden und dergleichen.

Spezielle Moves werden seltener zum Einsatz kommen.
Sie behandeln Sachen wie Stufenaufstiege, das Unternehmen einer langen Reise oder die Rückkehr in die Stadt nach einem Abenteuer.

Alle Spielercharaktere können grundlegende und spezielle Moves benutzen.
Zusätzlich hat jeder Spielercharakter Moves, die ihm von seiner Klasse zur Verfügung gestellt werden – die werden wir uns später genauer anschauen.

Wir werden jeden Move zuerst beim Namen nennen, danach folgt eine Beschreibung seiner Regeln.
Einige Moves werden begleitet von einer kurzen Erläuterung ihrer Nutzung und einem Spielbeispiel.

=== Grundlegende Moves

.Hauen und Stechen
****
*Wenn du einen Gegner im Nahkampf angreifst,* würfle+STÄ.
✴ Bei einer 10+ fügst du deinem Gegner Schaden zu und entrinnst seinem Angriff.
Wenn du willst, kannst du außerdem +1W6 Schaden machen, setzt dich dabei aber dem Angriff deines Gegners aus.
✴ Bei einer 7–9 fügst du deinem Gegner Schaden zu und dein Gegner kann einen Angriff gegen dich ausführen.
****

_Hauen und Stechen_ ist dazu da, einen wehrhaften Feind anzugreifen – schlicht und einfach.
Wenn dein Gegner sich nicht wehren kann – weil er nicht weiß, dass du da bist, oder weil er gefesselt und hilflos ist –, dann ist das kein _Hauen und Stechen_.
Du machst einfach deinen Schaden oder tötest ihn sofort, je nachdem, was die Situation gerade hergibt.
Böse Sache.

Der Angriff deines Gegners kann ein beliebiger Spielleiter-Move sein, solange er direkt von diesem Gegner ausgeht.
Ein Goblin schlägt vielleicht einfach zurück, oder er rammt dir eine vergiftete Nadel in die Seite.
Das Leben als Abenteurer ist nunmal kein Zuckerschlecken.

Beachte, dass ein "Angriff" eine Aktion eines Spielers beinhaltet, die dazu führen kann, dass jemand (oder etwas) anderes Schaden erleidet.
Ein Schwert gegen einen Drachen zu schwingen, dessen zentimeterdicke Schuppen mit magischer Energie vollgepumpt sind, lässt sich vergleichen mit dem Schwingen eines Fleischerbeils gegen einen Panzer:
Es wird ihm einfach keinen Schaden zufügen, also ist _Hauen und Stechen_ hier nicht anwendbar.
Das kann sich jedoch ändern, wenn die Umstände anders sind:
Wenn du so positioniert bist, dass du den weichen Bauch des Drachen angreifen kannst (viel Glück beim Dahinkommen!), kannst du ihm wehtun, und das ist dann ein Angriff.

Wenn es Sinn macht, dass du mit der Aktion, die den Move ausgelöst hat, mehrere Feinde angreifen kannst, würfle einmal und füge jedem Ziel den Schaden zu (abzüglich seiner Rüstung).

Manche Angriffe können – abhängig von der auslösenden Aktion, den Umständen oder den eingesetzten Waffen – zusätzliche Effekte haben:
Ein Angriff könnte jemanden niederschlagen, oder entwaffnen… oder nichts außer einem großen, blutigen Fleck hinterlassen.

____
SL: Jarl, du steckst bis zum Hals in geifernden Goblins.
Sie haben dich umzingelt und ihre Messer gezückt.
Was machst du?

Jarl: Mir reicht’s!
Ich verdresche den nächstbesten Goblin mit meinem Hammer.

SL: Okay.
Das ist eine Kampfsituation, also benutzt du Hauen und Stechen.
Würfle+STÄ.

Jarl: Eine 11.
Die Regeln sagen mir, dass ich eine Wahl treffen muss.
Furcht ist was für Schwächlinge, also lass diese Goblins nur kommen!

SL: Du lässt deinen Hammer in den nächstbesten Goblin krachen.
Deine Belohnung ist das befriedigende Geräusch seiner brechenden Knochen – das und eine Messerwunde, die du von seinem Gegenangriff bekommst.
Er richtet 4 Schadenspunkte bei dir an.
Was machst du?
____

____
SL: Cadeus, aus den Schatten kannst du diese Ork-Krieger überraschen.
Cadeus: Ich springe hervor lasse mein Schwert in hohem Bogen auf sie herabsausen.
Etwa so!
Yaaaah!

SL: Das hatten sie nicht erwartet, du hast sie komplett auf dem falschen Fuß erwischt und versenkst dein Schwert in einem von ihnen.
Würfle deinen Schaden.

Cadeus: Ich mache 6 Schaden.

SL: Der Ork fällt blutend zu Boden!
Der zweite stockt kurz, als er dich sieht.
Dann grinst er dich an, entblößt dabei seine widerlichen Hauer, und löst sein Signalhorn vom Gürtel!
Was machst du?
____

____
SL: Bartleby, du hast Finbar den Prächtigen, mächtigsten Duellanten des Landes, komplett entwaffnet und legst deine Klinge an seinem Hals.

Bartleby: Du wirst mich nicht noch einmal hintergehen, Finbar! Ich durchbohre ihn mit dem Schwert.

SL: Na gut, das ist dann Hauen und Stechen. Würfle+STÄ.

Bartleby: Na gut, wenn du das sagst… Ich habe eine 7.

SL: Okay, du durchbohrst ihn, weil er komplett wehrlos ist und… ähm, warte.
Weißt du was, er befindet sich gar nicht im Nahkampf mit dir.
Er ist hilflos, vergiss Hauen und Stechen, er ist erledigt.
Er sackt Blut spuckend zu Boden, aber der Alarm der Wache dringt in deine Ohren.
Was machst du?
____

.Salve
****
*Wenn du zielst und im Fernkampf auf einen Gegner schießt,* würfle+GES.
✴ Bei einer 10+ hast du ein freies Schussfeld – mache deinen Schaden.
✴ Bei einer 7–9, wähle eins (egal, was du wählst, du richtest deinen Schaden an):

* Du musst dich bewegen, um deinen Schuss anbringen zu können, und begibst dich dadurch in Gefahr (vom SL vorgegeben)
* Du musst nehmen, was du kriegen kannst: -1W6 Schaden
* Du musst mehrere Salven abfeuern: Reduziere deine Munition um 1
****

Eine _Salve_ beinhaltet den gesamten Akt des Spannens, Zielens und Feuerns einer Fernkampfwaffe, oder das Werfen einer Wurfwaffe.
Der Vorteil gegenüber dem Nahkampf besteht darin, dass der Angegriffene weniger Chancen hat, zurückzuschlagen.
Im Gegenzug muss ein Fernkämpfer auf seine Munition und ein freies Schussfeld achten.

Lege "Gefahr" großzügig aus, wenn jemand eine 7–9 würfelt.
Er könnte mit schlechtem Untergrund zu kämpfen haben oder am spitzen Ende einer Schwertklinge enden oder veilleicht auch nur gezwungen sein, den strategisch günstigen Glockenturm an den Feind aufzugeben.
Was auch immer die "Gefahr" ist, sie kommt näher und führt immer dazu, dass der SL die berühmte Frage stellt: "Was machst du?"
Oft wird dich die Situation dazu zwingen, dich voll und ganz auf ihre Abwendung zu konzentrieren oder der _Gefahr zu trotzen_.

Falls du etwas wirfst, das keine Munitionsanzeige hat (vielleicht hast du einen Move, der dir erlaubt, deinen Schild zu werfen), kannst du dir bei einer 7–9 nicht aussuchen, Munition abzustreichen.
Wähle stattdessen eine der beiden anderen Optionen.

____
Aranwe: Okay, ich sitze hier also fest auf dem Boden des Ritualariums, während der orkische Augenfresser oben auf dem Altar seinen Ritualgesang skandiert.
Da Thelian ja den Rest der Bande in Schach hält, lege ich meinen Bogen an, spanne und lasse einen Pfeil auf den singenden Ork los.

SL: Eine ausgezeichnete Wahl – klingt wie eine _Salve_ für mich.

Aranwe: Mist, eine 8.
Nun ja, ich hab kaum noch Pfeile und noch weniger Trefferpunkte.
Ich sollte nehmen, was ich kriegen kann.
Ich würfle meinen Schaden, dann ziehe vom Ergebnis 1W6 ab, richtig?
Ich habe eine 3.
Ist das wenigstens genug, um ihn abzulenken?

SL: Sicher! Der Pfeil gräbt sich ins Bein des Augenfressers und er brüllt vor Schmerzen, was das Ritual jäh unterbricht.
Unglücklicherweise scheint es, als hätte die Unterbrechung das Ganze nur schlimmer gemacht – ein fürchterliches Grollen hallt aus der Grube unter dem Altar und das Gebälk des Raums fängt an zu bröckeln.
Was machst du?
____
____
Halek: Kobolde und ein Oger?
Oh mann, was ist hier nur los?
Na gut, wenn sie auf mich aus sind, kann ich genauso gut meinen Bogen Hallo sagen lassen.
Ich jage einen Pfeil in den Mob und würfle… eine 8.

SL: Okay, was darf's sein? Gefahr? Munition?

Halek: Ich wähle… die Gefahr.

SL: Gut.
Die Kobolde umzingeln dich, aber dir gelingt es, einem von ihnen einen Schuss zu versetzen.
Er fällt, aber in dem Moment, als der Rest über dich kommt, fällt dir siedendheiß auf, dass du den Oger aus den Augen verloren hast.
Er schmettert seine Keule in deine Seite und du nimmst 12 Schaden!

Halek: 12 Schaden? Das ist die Gefahr?

SL: Du hast recht, das ist nicht wirklich eine Gefahr.
Okay, du bist noch kein Brei – der Oger baut sich drohend hinter dir auf und seine Keule saust auf deinen Schädel herab!
Was machst du?
____

.Gefahr trotzen
****
*Wenn du trotz einer unmittelbaren Gefahr handelst oder ein drohendes Unheil hinnehmen musst*, beschreibe, wie du damit umgehst, und würfle.
Wenn du der Gefahr entgehst, indem du…

* dich durchschlägst, würfle+STÄ
* ihr aus dem Weg gehst oder durch Schnelligkeit entrinnst, würfle+GES
* sie zähneknirschend hinnimmst, würfle+KON
* geistesgegenwärtig handelst, würfle+INT
* schiere Willenskraft aufbietest, würfle+WEI
* deine Ausstrahlung zu deinem Vorteil nutzt, würfle+CHA

✴ Bei einer 10+ gelingt dein Vorhaben, und die Bedrohung verhallt unerfüllt.
✴ Bei einer 7–9 stolperst, zögerst oder taumelst du:
Der SL wird dir einen ungünstigeren Ausgang oder einen teuren Handel anbieten, oder dich vor die Wahl zwischen zwei Übeln stellen.
****

Du _trotzt Gefahr_, wenn du etwas im Angesicht drohenden Unheils machst.
Das mag klingen wie ein viel zu vager Sammelbegriff, aber genau das ist die Absicht dahinter!
_Gefahr trotzen_ ist dann angebracht, wenn man das Gefühl hat, jetzt würfeln zu müssen, sich aber kein anderer Move anbietet.

_Gefahr trotzen_ wird auch verwendet, wenn man einen anderen Move macht und dabei Schwierigkeiten begegnet, die durch ihn nicht abgedeckt sind.
Zum Beispiel unterstellt der Move _Hauen und Stechen_ einen Schlagabtausch im Nahkampf:
Du musst nicht jedes mal _Gefahr trotzen_, wenn du dem Angriff des Monsters ausweichen willst; es sei denn, es ist eine Gefahr im Spiel, die nicht direkt etwas mit dem Angriff des Monsters zu tun hat.
Wenn du andererseits zu _hauen und stechen_ versuchst, während scharfkantige Speere aus Löchern in der Wand schießen, dann sind diese Speere sehr wohl eine _Gefahr_, der _getrotzt_ werden muss.

Eine "Gefahr" ist dabei alles, was Widerstandsfähigkeit, Konzentration oder Gleichgewichtssinn erfordert.
Dieser Move wird üblicherweise vom SL gefordert.
Er wird dir sagen, was in dieser Situation die konkrete Gefahr ist, der du gegenüberstehst.
In etwa so:
"Du wirst erstmal _Gefahr trotzen_ müssen.
Die Gefahr ist der steile, vereiste Boden, über den du rennen willst.
Wenn du es schaffst, auf den Füßen zu bleiben, schaffst du es auch, die Tür zu erreichen, bevor der Nekromant es schafft, seine Magie auf dich loszulassen."

Das verwendete Attribut wird von der Art und Weise festgelegt, mit der du der Gefahr begegnest.
Deine Aktion muss dabei den Move auslösen.
Das bedeutet, dass du der Gefahr eines abschüssigen, vereisten Bodens nicht einfach trotzen kannst, indem du ein gewinnendes Lächeln aufsetzt, nur weil CHA dein bester Wert ist:
Den Boden charmant anzulächeln hat keine Wirkung.
Stattdessen könntest du mit STÄ einen gewaltigen Satz über die vereiste Stelle machen, mit GES vorsichtig hinüberbalancieren, und so weiter.
Indem du den Move vollführst, bekommst du das Ergebnis.

____
SL: Emory, während du die Seite der Schlucht erklimmst, erblickst du einen Kultisten auf einem nahen Vorsprung.
Er beschwört einen Frostzauber und bedeckt die gesamte Wand mit Eis!
Wenn du deine Kletterpartie fortsetzen willst, musst du der _Gefahr trotzen_ oder du riskierst, zu fallen.

Emory: Auf keinen Fall, dazu bin ich viel zu abgebrüht.
Ich beiße die Zähne zusammen und kralle meine Finger in die Wand, immer eine Hand nach der anderen.
Ich benutze KON, okay?
Ich habe aber leider eine 8 gewürfelt…

SL: Hmm, na gut, du harter Kerl.
Du wirst nur ganz nach oben kommen, wenn du deinen Dolch benutzt, um dich die letzten paar Meter hinaufzuziehen.
Der Dolch wird dort in der Wand stecken bleiben, bis du Zeit hast, ihn herauszuziehen – und im Moment will dir ein wütender Zauberwirker an den Kragen.

Emory: Ich kann mir ja einen neuen Dolch holen, wenn ich wieder zu Hause bin.
Zeit, die Kletterpartie abzuschließen und diesem Kultisten den Garaus zu machen.
____
____
SL: Der Athach schwingt seinen muskelbewehrten dritten Arm gegen dich, die knorrigen Finger fest um einen dicken Ast geschlossen.
Was machst du, Valeria?

Valeria: Er will also kämpfen, wie?
Dann mal los.
Ich _haue und steche_, indem ich mein Schwert gegen seine Beine schwinge.

SL: Moment mal, Freundchen.
Er hat dich schon auf dem falschen Fuß erwischt.
Du kannst dich zwar ins Getümmel stürzen, aber er wird dir den Schädel einschlagen, solange du dieser _Gefahr_ nicht _trotzt_.

Valeria: Pff, der Kerl ist Valeria der Roten doch nicht gewachsen!
Ich springe zur Seite wie ein Blatt im Wind und _haue und steche_ dann.

SL: _Trotze_ der _Gefahr_ mit GES, bitte und danke.
____
____
Octavia: Ich habe genug von diesem Oger!
Ich lasse meinen Schild fallen und schwinge meinen Hammer mit beiden Händen.
Das ist _Hauen und Stechen_, nicht wahr?

SL: Du lässt deinen Schild fallen?
Das ist kein guter Einfall – jetzt musst du _Gefahr trotzen_, oder der Oger wird dich treffen.

Octavia: Bist du sicher?
Ist das nicht genau die Situation, die von _Hauen und Stechen_ abgedeckt wird – Schlagabtausche und so?

SL: Oh, ja, natürlich.
Ich glaube, ich brauche noch einen Kaffee.
_Hauen und Stechen_ dann bitte, mach deinen Zug!
____

.Verteidigen
****
*Wenn du eine Person, einen Gegenstand oder einen Ort vor Angriffen bewahren willst,* würfle+KON.
✴ Bei einer 10+ erhältst du 3 Reserve.
✴ Bei einer 7–9 erhältst du 1 Reserve.
Solange du verteidigst, kannst du, wenn du oder dein Ziel angegriffen werden, Reserve 1 zu 1 ausgeben und von folgender Liste wählen:

* Lenke einen Angriff von deinem Ziel auf dich um.
* Halbiere den Schaden oder den Effekt des Angriffs.
* Reiße eine Lücke in die Verteidigung deines Angreifers und gib einem Verbündeten +1 vorwärts gegen ihn.
* Füge deinem Angreifer soviel Schaden zu, wie du Stufen hast.
****

Etwas zu verteidigen bedeutet, dass du in der Nähe bleibst und dich darauf konzentrierst, Angriffe auf dein Ziel zu vermeiden oder zu verhindern, dass jemand ihm zu nahe kommt.
Wenn du dich nicht mehr in der Nähe befindest oder deine Aufmerksamkeit etwas anderem zuwendest, verlierst du deine Reserve.

Du kannst nur dann Reserve ausgeben, wenn jemand dich oder dein zu schützendes Ziel angreift.
Die Möglichkeiten, die dir dann zur Wahl stehen, hängen vom Angreifer und der Art des Angriffs ab:
Insbesondere kannst du deinem Angreifer keinen Schaden zufügen, wenn er außerhalb der Reichweite deiner Waffe ist.

Ein Angriff ist jede Aktion, in die du eingreifen kannst und die einen schädlichen Effekt hat.
Schwertschläge und Pfeilsalven sind natürlich Angriffe, aber auch Zaubersprüche, Haltegriffe oder Anstürme.

Bei einem Angriff, der keinen direkten Schaden verursacht, bedeutet "den Effekt halbieren", dass der Angreifer zum Teil das erreicht, was er will – aber eben nur zum Teil.
Was das letztendlich bedeutet, musst du zusammen mit deinem SL ausmachen.
Wenn du das Edelsteinauge von Oro-Uht verteidigst und ein Ork versucht, es von seinem Sockel zu schnappen, dann könnte ein "halbierter Effekt" bedeuten, dass das Auge von seinem Sockel gestoßen wird und davonrollt, ohne dass der Ork es in die Hände bekommt.
Oder der Ork bekommt es in die Hände, du allerdings auch:
jetzt kämpft ihr beide darum, bitterlich und mit Händen und Füßen.
Wenn du und der SL euch nicht auf einen halbierten Effekt einigen könnt, kannst du diese Option nicht aus der Liste wählen.

Dich selbst zu verteidigen ist natürlich ebenfalls möglich.
Esläuft darauf hinaus, dass du deinen Angriff aufgibst und einfach nur versuchst, dich selbst am Leben zu halten.

____
SL: Avon, während zu deinem Zauberspruch anhebst, mit dem du den Geist des Nekromanten zurück durch das Portal drängen willst, stürzen sich die Zombies auf dich.

Lux: Hab keine Furcht, kleiner Avon, ich werde dich retten.
Während Avon seinen Zauber spricht, schwöre ich, ihn zu beschützen – ich schlage meinen Hammer gegen meinen Schild und rufe "Wenn ihr ihn aufhalten wollt, müsst ihr erst einmal an mir vorbei!"
Ich möchte Avon verteidigen.

SL: Und mit Gusto, wie ich sehe!
Würfle+KON.

Lux: Ich habe eine 11 gewürfelt.
3 Reserve, stimmt's?

Avon: Mach dich schon mal bereit, die auch zu nutzen.
Ich habe eine 8 beim Zaubern gewürfelt – und ich würde mich gern in Gefahr begeben.

SL: Natürlich willst du das.
Die Zombies werden von den magischen Energien angezogen und taumeln zum Angriff in deine Richtung.
Plötzlich bist du von ihnen umringt, sie sind überall!
Was machst du?

Avon: Hilflos quieken?

Lux: Bin ja schon da.
Ich gebe einen Punkt Reserve aus, um den Angriff auf mich umzulenken:
Ich schubse Avon zur Seite und lasse die ganze Wut meiner Gottheit in Wellen über die Untoten hereinbrechen, was sie nur noch mehr erzürnt.
Um auf der sicheren Seite zu sein, schwinge ich meinen Hammer im Halbkreis und richte meinen Schaden an.
Wenn ich schonmal dabei bin, kann ich auch den letzten Punkt ausgeben und den Schaden auf mich halbieren.
Mein Gott wacht über uns!
____
____
SL: Also, Hadrian, du hast Durga _verteidigt_, während sie Willem geheilt hat, aber Willem geht es jetzt besser.
Was machst du?

Durga: Ich stürze mich auf die Troglodyten, um sie zurückzutreiben!

Hadrian: Ich will mich mit diesem Krokodilmenschen anlegen.

SL: Okay, Durga, die Trogs stürzen dir entgegen mit ihren Keulen.

Hadrian: Auf keinen Fall, ich habe noch Reserve übrig – die will ich benutzen, um den Angriff auf mich umzuleiten.

SL: Ihr zwei seid jetzt zu weit auseinander.
Wie willst du das anstellen, wenn du 20 Meter von ihr entfernt bist?
Du hast deine Reserve verloren, als du den Krokodilmenschen angegriffen hast, mein Freund.

Hadrian: Na gut, ich schätze, ich stehe ihr nicht mehr "zur Seite".
Vergiss es, Durga, du bist auf dich allein gestellt!
____

.Wissen verkünden
****
*Wenn du dein angesammeltes Wissen über etwas konsultierst*, würfle+INT.
✴ Bei einer 10+ wird dir der SL etwas Interessantes und Nützliches über das Objekt deiner Neugier erzählen, das für deine momentane Situation von Belang ist.
✴ Bei einer 7–9 wird er dir nur etwas Interessantes darüber erzählen – es liegt an dir, die Information zu deinem Vorteil zu nutzen.
Der SL könnte dich fragen "Woher weißt du das?"
Sag ihm die Wahrheit, und zwar jetzt.
****

Du _verkündest_ dein _Wissen_ immer dann, wenn du in deinem Gedächtnis nach Wissen oder Fakten über etwas kramst.
Du könntest dir zum Beispiel einen Moment Zeit nehmen, um darüber nachzudenken, was du über die Orkischen Stämme oder die Türme von Ul'dammar weißt, und enthüllst dann dieses Wissen.

Die dabei erhaltenen Informationen sind der Art, wie du sie auch in einer Bibliothek, einem Reiseführer oder einem Bestiarium finden würdest.
Bei einer 10+ zeigt dir der SL, wie dieses Wissen unmittelbar nützlich für dich sein kann; bei einer 7–9 ist es Wissen ohne direkten Nutzen oder ohne einen Bezug zur momentanen Situation.

Bei einem Fehlschlag wird die Reaktion des SL oft die Zeit beinhalten, die du mit Nachdenken zugebracht hast.
Vielleicht hast du nicht mitbekommen, wie dieser Goblin sich hinter dich geschlichen hat, oder du hast den Stolperdraht übersehen, der quer über den Gang gespannt ist.
Solche Momente sind außerdem eine großartige Gelegenheit, eine unangenehme Wahrheit zu enthüllen.

Nur für den Fall, dass es noch nicht klar sein sollte:
Die Antworten des SL sind immer wahr, auch dann, wenn er sie aus dem Stegreif erfinden musste.
Für den SL gilt hier: Sei aufrichtig deinen Spielern gegenüber.

____
Fenfaril: Der Boden war eine Illusion?
Diese verfluchten Gnome.
Ich verfluche sie bis dahin, wo auch immer Gnome gehen, wenn sie tot sind.

SL: Haha, yep.
Du bist in einer düsteren Grube, und eine humanoide Gestalt, fleckig und augenlos, schleppt sich murmelnd auf dich zu.

Fenfaril: Murmelnde Gestalt, was?
Was ist das für ein Ding?
Will es mich angreifen?
Ich bin mir sicher, von so etwas schon einmal gelesen zu haben.
Vielleicht in der Schule?

SL: Kann schon sein.
Künde uns von deinem Wissen!

Fenfaril: Lasse mir dein Wissen zuteil werden, o Hirn.
Ich habe eine 8 gewürfelt.

SL: Nun ja, natürlich hast du von diesen Dingen schon gehört – der Name entfällt dir, aber du kannst dich eindeutig an eine Zeichnung einer solchen Kreatur erinnern.
Es war in einer Art großem Flur und hat etwas bewacht.
Du weißt, dass es irgendeinen Trick geben muss, mit dem du es dazu bringen kannst, dich vorbeizulassen, aber die Details wollen dir einfach nicht einfallen.
Warum nicht?

Fenfaril: Offensichtlich hatte ich an dem Tag einen Kater.
Ich war ein mieser Student.
Ein Trick, sagst du?
Hmm…
____
____
Vitus: Ich habe eine 10 auf meinen _Wissen verkünden_-Wurf für diesen vergoldeten Schädel.

SL: Du bist dir ziemlich sicher, dass du die Metallarbeiten von Dis, der lebenden Stadt, wiedererkennst.

Vitus: …und weiter? Ich habe eine 10 bekommen!

SL: Natürlich, stimmt ja.
Also, um genau zu sein, erkennst du ein paar ganz bestimmte Glyphen wieder.
Sie stellen Ifriti dar, Spuren eines Feuerzaubers, aber sie sind irgendwie anders – eine Art Verwandlungsmagie.
Ich wette, wenn du einen Zauber in den Schädel hineinzauberst, wird er zu einem Feuerzauber.

Vitus: Magische Geschosse des Feuers – hurra!
____
