
== Grundlegende Züge

Dieses Kapitel enthält Züge, die allen Charakteren zur Verfügung stehen.
Sie lassen sich in zwei Kategorien unterteilen: Grundlegende und spezielle.

Grundlegende Züge machen den Löwenanteil des Abenteurerlebens aus.
Sie kommen zur Anwendung in Kämpfen, angespannten Verhandlungen, gefährlichen Gegenden und dergleichen.

Spezielle Züge werden seltener zum Einsatz kommen.
Sie behandeln Sachen wie Stufenaufstiege, das Unternehmen einer langen Reise oder die Rückkehr in die Stadt nach einem Abenteuer.

Alle Spielercharaktere können grundlegende und spezielle Züge benutzen.
Zusätzlich hat jeder Spielercharakter Züge, die ihm von seiner Klasse zur Verfügung gestellt werden – die werden wir uns später genauer anschauen.

Wir werden jeden Zug zuerst beim Namen nennen, danach folgt eine Beschreibung seiner Regeln.
Einige Züge werden begleitet von einer kurzen Erläuterung ihrer Nutzung und einem Spielbeispiel.

=== Grundlegende Züge

.Hauen und Stechen
****
*Wenn du einen Gegner im Nahkampf angreifst,* würfle+STÄ.
✴ Bei einer 10+ fügst du deinem Gegner Schaden zu und entrinnst seinem Angriff.
Wenn du willst, kannst du außerdem +1W6 Schaden machen, setzt dich dabei aber dem Angriff deines Gegners aus.
✴ Bei einer 7–9 fügst du deinem Gegner Schaden zu und dein Gegner kann einen Angriff gegen dich ausführen.
****

_Hauen und Stechen_ ist dazu da, einen wehrhaften Feind anzugreifen – schlicht und einfach.
Wenn dein Gegner sich nicht wehren kann – weil er nicht weiß, dass du da bist, oder weil er gefesselt und hilflos ist –, dann ist das kein _Hauen und Stechen_.
Du machst einfach deinen Schaden oder tötest ihn sofort, je nachdem, was die Situation gerade hergibt.
Böse Sache.

Der Angriff deines Gegners kann ein beliebiger Spielleiter-Zug sein, solange er direkt von diesem Gegner ausgeht.
Ein Goblin schlägt vielleicht einfach zurück, oder er rammt dir eine vergiftete Nadel in die Seite.
Das Leben als Abenteurer ist nunmal kein Zuckerschlecken.

Beachte, dass ein "Angriff" eine Aktion eines Spielers beinhaltet, die dazu führen kann, dass jemand (oder etwas) anderes Schaden erleidet.
Ein Schwert gegen einen Drachen zu schwingen, dessen zentimeterdicke Schuppen mit magischer Energie vollgepumpt sind, lässt sich vergleichen mit dem Schwingen eines Fleischerbeils gegen einen Panzer:
Es wird ihm einfach keinen Schaden zufügen, also ist _Hauen und Stechen_ hier nicht anwendbar.
Das kann sich jedoch ändern, wenn die Umstände anders sind:
Wenn du so positioniert bist, dass du den weichen Bauch des Drachen angreifen kannst (viel Glück beim Dahinkommen!), kannst du ihm wehtun, und das ist dann ein Angriff.

Wenn es Sinn macht, dass du mit der Aktion, die den Zug ausgelöst hat, mehrere Feinde angreifen kannst, würfle einmal und füge jedem Ziel den Schaden zu (abzüglich seiner Rüstung).

Manche Angriffe können – abhängig von der auslösenden Aktion, den Umständen oder den eingesetzten Waffen – zusätzliche Effekte haben:
Ein Angriff könnte jemanden niederschlagen, oder entwaffnen… oder nichts außer einem großen, blutigen Fleck hinterlassen.

____
SL: Jarl, du steckst bis zum Hals in geifernden Goblins.
Sie haben dich umzingelt und ihre Messer gezückt.
Was machst du?

Jarl: Mir reicht’s!
Ich verdresche den nächstbesten Goblin mit meinem Hammer.

SL: Okay.
Das ist eine Kampfsituation, also benutzt du Hauen und Stechen.
Würfle+STÄ.

Jarl: Eine 11.
Die Regeln sagen mir, dass ich eine Wahl treffen muss.
Furcht ist was für Schwächlinge, also lass diese Goblins nur kommen!

SL: Du lässt deinen Hammer in den nächstbesten Goblin krachen.
Deine Belohnung ist das befriedigende Geräusch seiner brechenden Knochen – das und eine Messerwunde, die du von seinem Gegenangriff bekommst.
Er richtet 4 Schadenspunkte bei dir an.
Was machst du?
____

____
SL: Cadeus, aus den Schatten kannst du diese Ork-Krieger überraschen.
Cadeus: Ich springe hervor lasse mein Schwert in hohem Bogen auf sie herabsausen.
Etwa so!
Yaaaah!

SL: Das hatten sie nicht erwartet, du hast sie komplett auf dem falschen Fuß erwischt und versenkst dein Schwert in einem von ihnen.
Würfle deinen Schaden.

Cadeus: Ich mache 6 Schaden.

SL: Der Ork fällt blutend zu Boden!
Der zweite stockt kurz, als er dich sieht.
Dann grinst er dich an, entblößt dabei seine widerlichen Hauer, und löst sein Signalhorn vom Gürtel!
Was machst du?
____

____
SL: Bartleby, du hast Finbar den Prächtigen, mächtigsten Duellanten des Landes, komplett entwaffnet und legst deine Klinge an seinem Hals.

Bartleby: Du wirst mich nicht noch einmal hintergehen, Finbar! Ich durchbohre ihn mit dem Schwert.

SL: Na gut, das ist dann Hauen und Stechen. Würfle+STÄ.

Bartleby: Na gut, wenn du das sagst… Ich habe eine 7.

SL: Okay, du durchbohrst ihn, weil er komplett wehrlos ist und… ähm, warte.
Weißt du was, er befindet sich gar nicht im Nahkampf mit dir.
Er ist hilflos, vergiss Hauen und Stechen, er ist erledigt.
Er sackt Blut spuckend zu Boden, aber der Alarm der Wache dringt in deine Ohren.
Was machst du?
____

.Salve
****
*Wenn du zielst und im Fernkampf auf einen Gegner schießt,* würfle+GES.
✴ Bei einer 10+ hast du ein freies Schussfeld – mache deinen Schaden.
✴ Bei einer 7–9, wähle eins (egal, was du wählst, du richtest deinen Schaden an):

* Du musst dich bewegen, um deinen Schuss anbringen zu können, und begibst dich dadurch in Gefahr (vom SL vorgegeben)
* Du musst nehmen, was du kriegen kannst: -1W6 Schaden
* Du musst mehrere Salven abfeuern: Reduziere deine Munition um 1
****

Eine _Salve_ beinhaltet den gesamten Akt des Spannens, Zielens und Feuerns einer Fernkampfwaffe, oder das Werfen einer Wurfwaffe.
Der Vorteil gegenüber dem Nahkampf besteht darin, dass der Angegriffene weniger Chancen hat, zurückzuschlagen.
Im Gegenzug muss ein Fernkämpfer auf seine Munition und ein freies Schussfeld achten.

Lege "Gefahr" großzügig aus, wenn jemand eine 7–9 würfelt.
Er könnte mit schlechtem Untergrund zu kämpfen haben oder am spitzen Ende einer Schwertklinge enden oder veilleicht auch nur gezwungen sein, den strategisch günstigen Glockenturm an den Feind aufzugeben.
Was auch immer die "Gefahr" ist, sie kommt näher und führt immer dazu, dass der SL die berühmte Frage stellt: "Was machst du?"
Oft wird dich die Situation dazu zwingen, dich voll und ganz auf ihre Abwendung zu konzentrieren oder der _Gefahr zu trotzen_.

Falls du etwas wirfst, das keine Munitionsanzeige hat (vielleicht hast du einen Zug, der dir erlaubt, deinen Schild zu werfen), kannst du dir bei einer 7–9 nicht aussuchen, Munition abzustreichen.
Wähle stattdessen eine der beiden anderen Optionen.

____
Aranwe: Okay, ich sitze hier also fest auf dem Boden des Ritualariums, während der orkische Augenfresser oben auf dem Altar seinen Ritualgesang skandiert.
Da Thelian ja den Rest der Bande in Schach hält, lege ich meinen Bogen an, spanne und lasse einen Pfeil auf den singenden Ork los.

SL: Eine ausgezeichnete Wahl – klingt wie eine _Salve_ für mich.

Aranwe: Mist, eine 8.
Nun ja, ich hab kaum noch Pfeile und noch weniger Trefferpunkte.
Ich sollte nehmen, was ich kriegen kann.
Ich würfle meinen Schaden, dann ziehe vom Ergebnis 1W6 ab, richtig?
Ich habe eine 3.
Ist das wenigstens genug, um ihn abzulenken?

SL: Sicher! Der Pfeil gräbt sich ins Bein des Augenfressers und er brüllt vor Schmerzen, was das Ritual jäh unterbricht.
Unglücklicherweise scheint es, als hätte die Unterbrechung das Ganze nur schlimmer gemacht – ein fürchterliches Grollen hallt aus der Grube unter dem Altar und das Gebälk des Raums fängt an zu bröckeln.
Was machst du?
____
____
Halek: Kobolde und ein Oger?
Oh mann, was ist hier nur los?
Na gut, wenn sie auf mich aus sind, kann ich genauso gut meinen Bogen Hallo sagen lassen.
Ich jage einen Pfeil in den Mob und würfle… eine 8.

SL: Okay, was darf's sein? Gefahr? Munition?

Halek: Ich wähle… die Gefahr.

SL: Gut.
Die Kobolde umzingeln dich, aber dir gelingt es, einem von ihnen einen Schuss zu versetzen.
Er fällt, aber in dem Moment, als der Rest über dich kommt, fällt dir siedendheiß auf, dass du den Oger aus den Augen verloren hast.
Er schmettert seine Keule in deine Seite und du nimmst 12 Schaden!

Halek: 12 Schaden? Das ist die Gefahr?

SL: Du hast recht, das ist nicht wirklich eine Gefahr.
Okay, du bist noch kein Brei – der Oger baut sich drohend hinter dir auf und seine Keule saust auf deinen Schädel herab!
Was machst du?
____

.Gefahr trotzen
****
*Wenn du trotz einer unmittelbaren Gefahr handelst oder ein drohendes Unheil hinnehmen musst*, beschreibe, wie du damit umgehst, und würfle.
Wenn du der Gefahr entgehst, indem du…

* dich durchschlägst, würfle+STÄ
* ihr aus dem Weg gehst oder durch Schnelligkeit entrinnst, würfle+GES
* sie zähneknirschend hinnimmst, würfle+KON
* geistesgegenwärtig handelst, würfle+INT
* schiere Willenskraft aufbietest, würfle+WEI
* deine Ausstrahlung zu deinem Vorteil nutzt, würfle+CHA

✴ Bei einer 10+ gelingt dein Vorhaben, und die Bedrohung verhallt unerfüllt.
✴ Bei einer 7–9 stolperst, zögerst oder taumelst du:
Der SL wird dir einen ungünstigeren Ausgang oder einen teuren Handel anbieten, oder dich vor die Wahl zwischen zwei Übeln stellen.
****

Du _trotzt Gefahr_, wenn du etwas im Angesicht drohenden Unheils machst.
Das mag klingen wie ein viel zu vager Sammelbegriff, aber genau das ist die Absicht dahinter!
_Gefahr trotzen_ ist dann angebracht, wenn man das Gefühl hat, jetzt würfeln zu müssen, sich aber kein anderer Zug anbietet.

_Gefahr trotzen_ wird auch verwendet, wenn man einen anderen Zug macht und dabei Schwierigkeiten begegnet, die durch ihn nicht abgedeckt sind.
Zum Beispiel unterstellt der Zug _Hauen und Stechen_ einen Schlagabtausch im Nahkampf:
Du musst nicht jedes mal _Gefahr trotzen_, wenn du dem Angriff des Monsters ausweichen willst; es sei denn, es ist eine Gefahr im Spiel, die nicht direkt etwas mit dem Angriff des Monsters zu tun hat.
Wenn du andererseits zu _hauen und stechen_ versuchst, während scharfkantige Speere aus Löchern in der Wand schießen, dann sind diese Speere sehr wohl eine _Gefahr_, der _getrotzt_ werden muss.

Eine "Gefahr" ist dabei alles, was Widerstandsfähigkeit, Konzentration oder Gleichgewichtssinn erfordert.
Dieser Zug wird üblicherweise vom SL gefordert.
Er wird dir sagen, was in dieser Situation die konkrete Gefahr ist, der du gegenüberstehst.
In etwa so:
"Du wirst erstmal _Gefahr trotzen_ müssen.
Die Gefahr ist der steile, vereiste Boden, über den du rennen willst.
Wenn du es schaffst, auf den Füßen zu bleiben, schaffst du es auch, die Tür zu erreichen, bevor der Nekromant es schafft, seine Magie auf dich loszulassen."

Das verwendete Attribut wird von der Art und Weise festgelegt, mit der du der Gefahr begegnest.
Deine Aktion muss dabei den Zug auslösen.
Das bedeutet, dass du der Gefahr eines abschüssigen, vereisten Bodens nicht einfach trotzen kannst, indem du ein gewinnendes Lächeln aufsetzt, nur weil CHA dein bester Wert ist:
Den Boden charmant anzulächeln hat keine Wirkung.
Stattdessen könntest du mit STÄ einen gewaltigen Satz über die vereiste Stelle machen, mit GES vorsichtig hinüberbalancieren, und so weiter.
Indem du den Zug vollführst, bekommst du das Ergebnis.

____
SL: Emory, während du die Seite der Schlucht erklimmst, erblickst du einen Kultisten auf einem nahen Vorsprung.
Er beschwört einen Frostzauber und bedeckt die gesamte Wand mit Eis!
Wenn du deine Kletterpartie fortsetzen willst, musst du der _Gefahr trotzen_ oder du riskierst, zu fallen.

Emory: Auf keinen Fall, dazu bin ich viel zu abgebrüht.
Ich beiße die Zähne zusammen und kralle meine Finger in die Wand, immer eine Hand nach der anderen.
Ich benutze KON, okay?
Ich habe aber leider eine 8 gewürfelt…

SL: Hmm, na gut, du harter Kerl.
Du wirst nur ganz nach oben kommen, wenn du deinen Dolch benutzt, um dich die letzten paar Meter hinaufzuziehen.
Der Dolch wird dort in der Wand stecken bleiben, bis du Zeit hast, ihn herauszuziehen – und im Moment will dir ein wütender Zauberwirker an den Kragen.

Emory: Ich kann mir ja einen neuen Dolch holen, wenn ich wieder zu Hause bin.
Zeit, die Kletterpartie abzuschließen und diesem Kultisten den Garaus zu machen.
____
____
SL: Der Athach schwingt seinen muskelbewehrten dritten Arm gegen dich, die knorrigen Finger fest um einen dicken Ast geschlossen.
Was machst du, Valeria?

Valeria: Er will also kämpfen, wie?
Dann mal los.
Ich _haue und steche_, indem ich mein Schwert gegen seine Beine schwinge.

SL: Moment mal, Freundchen.
Er hat dich schon auf dem falschen Fuß erwischt.
Du kannst dich zwar ins Getümmel stürzen, aber er wird dir den Schädel einschlagen, solange du dieser _Gefahr_ nicht _trotzt_.

Valeria: Pff, der Kerl ist Valeria der Roten doch nicht gewachsen!
Ich springe zur Seite wie ein Blatt im Wind und _haue und steche_ dann.

SL: _Trotze_ der _Gefahr_ mit GES, bitte und danke.
____
____
Octavia: Ich habe genug von diesem Oger!
Ich lasse meinen Schild fallen und schwinge meinen Hammer mit beiden Händen.
Das ist _Hauen und Stechen_, nicht wahr?

SL: Du lässt deinen Schild fallen?
Das ist kein guter Einfall – jetzt musst du _Gefahr trotzen_, oder der Oger wird dich treffen.

Octavia: Bist du sicher?
Ist das nicht genau die Situation, die von _Hauen und Stechen_ abgedeckt wird – Schlagabtausche und so?

SL: Oh, ja, natürlich.
Ich glaube, ich brauche noch einen Kaffee.
_Hauen und Stechen_ dann bitte, mach deinen Zug!
____

.Verteidigen
****
*Wenn du eine Person, einen Gegenstand oder einen Ort vor Angriffen bewahren willst,* würfle+KON.
✴ Bei einer 10+ erhältst du 3 Reserve.
✴ Bei einer 7–9 erhältst du 1 Reserve.
Solange du verteidigst, kannst du, wenn du oder dein Ziel angegriffen werden, Reserve 1 zu 1 ausgeben und von folgender Liste wählen:

* Lenke einen Angriff von deinem Ziel auf dich um.
* Halbiere den Schaden oder den Effekt des Angriffs.
* Reiße eine Lücke in die Verteidigung deines Angreifers und gib einem Verbündeten +1 voraus gegen ihn.
* Füge deinem Angreifer soviel Schaden zu, wie du Stufen hast.
****

Etwas zu verteidigen bedeutet, dass du in der Nähe bleibst und dich darauf konzentrierst, Angriffe auf dein Ziel zu vermeiden oder zu verhindern, dass jemand ihm zu nahe kommt.
Wenn du dich nicht mehr in der Nähe befindest oder deine Aufmerksamkeit etwas anderem zuwendest, verlierst du deine Reserve.

Du kannst nur dann Reserve ausgeben, wenn jemand dich oder dein zu schützendes Ziel angreift.
Die Möglichkeiten, die dir dann zur Wahl stehen, hängen vom Angreifer und der Art des Angriffs ab:
Insbesondere kannst du deinem Angreifer keinen Schaden zufügen, wenn er außerhalb der Reichweite deiner Waffe ist.

Ein Angriff ist jede Aktion, in die du eingreifen kannst und die einen schädlichen Effekt hat.
Schwertschläge und Pfeilsalven sind natürlich Angriffe, aber auch Zaubersprüche, Haltegriffe oder Anstürme.

Bei einem Angriff, der keinen direkten Schaden verursacht, bedeutet "den Effekt halbieren", dass der Angreifer zum Teil das erreicht, was er will – aber eben nur zum Teil.
Was das letztendlich bedeutet, musst du zusammen mit deinem SL ausmachen.
Wenn du das Edelsteinauge von Oro-Uht verteidigst und ein Ork versucht, es von seinem Sockel zu schnappen, dann könnte ein "halbierter Effekt" bedeuten, dass das Auge von seinem Sockel gestoßen wird und davonrollt, ohne dass der Ork es in die Hände bekommt.
Oder der Ork bekommt es in die Hände, du allerdings auch:
jetzt kämpft ihr beide darum, bitterlich und mit Händen und Füßen.
Wenn du und der SL euch nicht auf einen halbierten Effekt einigen könnt, kannst du diese Option nicht aus der Liste wählen.

Dich selbst zu verteidigen ist natürlich ebenfalls möglich.
Esläuft darauf hinaus, dass du deinen Angriff aufgibst und einfach nur versuchst, dich selbst am Leben zu halten.

____
SL: Avon, während zu deinem Zauberspruch anhebst, mit dem du den Geist des Nekromanten zurück durch das Portal drängen willst, stürzen sich die Zombies auf dich.

Lux: Hab keine Furcht, kleiner Avon, ich werde dich retten.
Während Avon seinen Zauber spricht, schwöre ich, ihn zu beschützen – ich schlage meinen Hammer gegen meinen Schild und rufe "Wenn ihr ihn aufhalten wollt, müsst ihr erst einmal an mir vorbei!"
Ich möchte Avon verteidigen.

SL: Und mit Gusto, wie ich sehe!
Würfle+KON.

Lux: Ich habe eine 11 gewürfelt.
3 Reserve, stimmt's?

Avon: Mach dich schon mal bereit, die auch zu nutzen.
Ich habe eine 8 beim Zaubern gewürfelt – und ich würde mich gern in Gefahr begeben.

SL: Natürlich willst du das.
Die Zombies werden von den magischen Energien angezogen und taumeln zum Angriff in deine Richtung.
Plötzlich bist du von ihnen umringt, sie sind überall!
Was machst du?

Avon: Hilflos quieken?

Lux: Bin ja schon da.
Ich gebe einen Punkt Reserve aus, um den Angriff auf mich umzulenken:
Ich schubse Avon zur Seite und lasse die ganze Wut meiner Gottheit in Wellen über die Untoten hereinbrechen, was sie nur noch mehr erzürnt.
Um auf der sicheren Seite zu sein, schwinge ich meinen Hammer im Halbkreis und richte meinen Schaden an.
Wenn ich schonmal dabei bin, kann ich auch den letzten Punkt ausgeben und den Schaden auf mich halbieren.
Mein Gott wacht über uns!
____
____
SL: Also, Hadrian, du hast Durga _verteidigt_, während sie Willem geheilt hat, aber Willem geht es jetzt besser.
Was machst du?

Durga: Ich stürze mich auf die Troglodyten, um sie zurückzutreiben!

Hadrian: Ich will mich mit diesem Krokodilmenschen anlegen.

SL: Okay, Durga, die Trogs stürzen dir entgegen mit ihren Keulen.

Hadrian: Auf keinen Fall, ich habe noch Reserve übrig – die will ich benutzen, um den Angriff auf mich umzuleiten.

SL: Ihr zwei seid jetzt zu weit auseinander.
Wie willst du das anstellen, wenn du 20 Meter von ihr entfernt bist?
Du hast deine Reserve verloren, als du den Krokodilmenschen angegriffen hast, mein Freund.

Hadrian: Na gut, ich schätze, ich stehe ihr nicht mehr "zur Seite".
Vergiss es, Durga, du bist auf dich allein gestellt!
____

.Wissen verkünden
****
*Wenn du dein angesammeltes Wissen über etwas konsultierst*, würfle+INT.
✴ Bei einer 10+ wird dir der SL etwas Interessantes und Nützliches über das Objekt deiner Neugier erzählen, das für deine momentane Situation von Belang ist.
✴ Bei einer 7–9 wird er dir nur etwas Interessantes darüber erzählen – es liegt an dir, die Information zu deinem Vorteil zu nutzen.
Der SL könnte dich fragen "Woher weißt du das?"
Sag ihm die Wahrheit, und zwar jetzt.
****

Du _verkündest_ dein _Wissen_ immer dann, wenn du in deinem Gedächtnis nach Wissen oder Fakten über etwas kramst.
Du könntest dir zum Beispiel einen Moment Zeit nehmen, um darüber nachzudenken, was du über die Orkischen Stämme oder die Türme von Ul'dammar weißt, und enthüllst dann dieses Wissen.

Die dabei erhaltenen Informationen sind der Art, wie du sie auch in einer Bibliothek, einem Reiseführer oder einem Bestiarium finden würdest.
Bei einer 10+ zeigt dir der SL, wie dieses Wissen unmittelbar nützlich für dich sein kann; bei einer 7–9 ist es Wissen ohne direkten Nutzen oder ohne einen Bezug zur momentanen Situation.

Bei einem Fehlschlag wird die Reaktion des SL oft die Zeit beinhalten, die du mit Nachdenken zugebracht hast.
Vielleicht hast du nicht mitbekommen, wie dieser Goblin sich hinter dich geschlichen hat, oder du hast den Stolperdraht übersehen, der quer über den Gang gespannt ist.
Solche Momente sind außerdem eine großartige Gelegenheit, eine unangenehme Wahrheit zu enthüllen.

Nur für den Fall, dass es noch nicht klar sein sollte:
Die Antworten des SL sind immer wahr, auch dann, wenn er sie aus dem Stegreif erfinden musste.
Für den SL gilt hier: Sei aufrichtig deinen Spielern gegenüber.

____
Fenfaril: Der Boden war eine Illusion?
Diese verfluchten Gnome.
Ich verfluche sie bis dahin, wo auch immer Gnome gehen, wenn sie tot sind.

SL: Haha, yep.
Du bist in einer düsteren Grube, und eine humanoide Gestalt, fleckig und augenlos, schleppt sich murmelnd auf dich zu.

Fenfaril: Murmelnde Gestalt, was?
Was ist das für ein Ding?
Will es mich angreifen?
Ich bin mir sicher, von so etwas schon einmal gelesen zu haben.
Vielleicht in der Schule?

SL: Kann schon sein.
Künde uns von deinem Wissen!

Fenfaril: Lasse mir dein Wissen zuteil werden, o Hirn.
Ich habe eine 8 gewürfelt.

SL: Nun ja, natürlich hast du von diesen Dingen schon gehört – der Name entfällt dir, aber du kannst dich eindeutig an eine Zeichnung einer solchen Kreatur erinnern.
Es war in einer Art großem Flur und hat etwas bewacht.
Du weißt, dass es irgendeinen Trick geben muss, mit dem du es dazu bringen kannst, dich vorbeizulassen, aber die Details wollen dir einfach nicht einfallen.
Warum nicht?

Fenfaril: Offensichtlich hatte ich an dem Tag einen Kater.
Ich war ein mieser Student.
Ein Trick, sagst du?
Hmm…
____
____
Vitus: Ich habe eine 10 auf meinen _Wissen verkünden_-Wurf für diesen vergoldeten Schädel.

SL: Du bist dir ziemlich sicher, dass du die Metallarbeiten von Dis, der lebenden Stadt, wiedererkennst.

Vitus: …und weiter? Ich habe eine 10 bekommen!

SL: Natürlich, stimmt ja.
Also, um genau zu sein, erkennst du ein paar ganz bestimmte Glyphen wieder.
Sie stellen Ifriti dar, Spuren eines Feuerzaubers, aber sie sind irgendwie anders – eine Art Verwandlungsmagie.
Ich wette, wenn du einen Zauber in den Schädel hineinzauberst, wird er zu einem Feuerzauber.

Vitus: Magische Geschosse des Feuers – hurra!
____

.Tatsachen aufdecken
****
*Wenn du eine Situation oder Person eingehend studierst,* würfle+WEI.
✴ Bei einer 10+ darfst du dem SL drei Fragen von der Liste unten stellen.
✴ Bei einer 7–9 darfst du nur eine stellen.

Wenn du den Antworten entsprechend handelst, bekommst du +1 voraus.

* Was ist hier vor Kurzem geschehen?
* Was wird als Nächstes geschehen?
* Wovor sollte ich hier auf der Hut sein?
* Was hier ist nützlich oder wertvoll für mich?
* Wer hat hier wirklich das Sagen?
* Was hier ist nicht so, wie es zu sein scheint?
****

Um _Tatsachen aufzudecken_, musst du dein Ziel genau beobachten.
Das bedeutet üblicherweise, dass du damit interagieren musst (oder jemand anderem dabei zuschaust).
Du kannst nicht einfach deinen Kopf durch die Tür stecken und _Tatsachen_ über einen Raum _aufdecken_.
Du schaust nicht einfach nebenbei nach Hinweisen – du kramst unter alten Sitzbezügen und zwischen Polstern, klopfst Wände ab und hältst Ausschau nach verdächtigen Mustern im Staub, der sich auf Bücherregalen angesammelt hat.
Sowas eben.

Bei _Tatsachen aufdecken_ geht es auch nicht einfach um ein kleines Detail, sondern um das Erkennen von größeren Zusammenhängen.
Der SL beschreibt immer ehrlich, was die Spielercharaktere wahrnehmen – so wird er zum Beispiel in einem Kampf sagen, dass der Koboldmagier am anderen Ende des Raumes bleibt.
_Tatsachen aufdecken_ könnte den Grund dafür in Erfahrung bringen:
Die Bewegungen, die er vollführt, ziehen Energie aus dem Raum hinter ihm an, weswegen er nicht näher kommen kann.

Genau wie bei _Wissen verkünden_ sind die Antworten, die du vom SL erhältst, immer aufrichtig – auch dann, wenn er sie sich aus dem Stegreif einfallen lassen musste.
Sobald die Antwort im Raum steht, ist sie in Stein gemeißelt.
Du willst auch dann _Tatsachen aufdecken_, wenn du die Wahrheit hinter – auf magische oder andere Weise erzeugte – Illusionen herausfinden willst.

Solange in einem Zug nichts anderes behauptet wird, kannst du nur die Fragen an den SL richten, die in der Liste erscheinen.
Wenn du eine Frage stellst, die nicht auf der Liste ist, kann der SL dich entweder bitten, eine andere zu stellen oder dir eine Antwort geben, die zu einer Frage aus der Liste passt.

Es kann natürlich vorkommen, dass die Antwort auf eine Frage negativ ausfällt.
Das ist in Ordnung.
Wenn es tatsächlich nichts Nützliches oder Verwertbares in Erfahrung zu bringen gibt, wird der SL dir deine Frage mit "Nichts, tut mir leid" beantworten.

____
Omar: Ich traue diesem Raum nicht – ich werde mich hier mal ein bisschen umsehen.
Ich hole mein Werkzeug raus und fummle an der Einrichtung herum.
Ich ziehe an Kerzenhaltern, klopfe die Wand mit dem Hammer ab.
Meine üblichen Tricks eben.

SL: _Tatsachen aufdecken_?

Omar: Oh ja.
Ich decke _alle_ Tatsachen auf.
Ich habe eine 12.
Ich würde gern wissen, "was hier ist nicht, wie es zu sein scheint?".

SL: Also, es ist offensichtlich für dich, dass die Nordwand des Raumes eine hohle Stelle hat.
Das Mauerwerk ist neuer und der Mörtel frischer, wahrscheinlich eine versteckte Nische oder ein Durchgang.

Omar: Ich will noch eine stellen.
"Wer hat den Raum versiegelt?"

SL: Die Frage ist nicht auf der Liste, also tue ich so, als hättest du "Was ist hier vor Kurzem geschehen?" gefragt.
Als du dir das Mauerwerk anschaust, fällt dir auf, dass es scheinbar nach außen gedrückt wurde.
Die Arbeit wurde hastig und ohne Fertigkeit durchgeführt – dir scheint, als wäre es das Werk von Goblins gewesen.
Die einzige Möglichkeit, die dir einfällt, wie die Mauer so aus der Form geraten konnte, ist, wenn jemand oder etwas von innen dagegendrückt.

Omar: Also haben die Goblins sie entweder von der anderen Seite verschlossen, oder da drin ist etwas, was versucht hat, zu fliehen.
____

.Schachern
****
*Wenn du ein Druckmittel gegen jemanden in der Hand hast und ihn damit manipulierst,* würfle+CHA.
Ein Druckmittel ist etwas, das derjenige benötigt oder haben will.
✴ Bei einer 10+ tut er, was du sagst, solange du ihm im Gegenzug etwas versprichst.
✴ Bei einer 7–9 wird er tun, was du sagst – aber nur dann, wenn du ihm hier und jetzt einen konkreten Beweis für dein Versprechen gibst.
****

_Schachern_ umfasst viele Situationen, darunter alte Bekannte wie Einschüchtern oder Diplomatie.
Du weißt, dass du Schachern benutzt, wenn du jemanden mit Hilfe eines Versprechens oder einer Drohung dazu bewegen willst, etwas Bestimmtes zu tun.
Dein Druckmittel kann dabei nett oder nicht so nett gemeint sein; der Umgangston spielt keine Rolle.

Wenn du jemanden lieb fragst, ist das noch kein _Schachern_, sondern einfach eine Unterhaltung.
Du fragst, "Kann ich dieses magische Schwert haben?" und Sir Telric antwortet, "Um Gottes Willen, das ist ein Erbstück, mein Vater hat es geschmiedet und meine Mutter es verzaubert!" und das war's.
Um mit jemandem zu schachern, musst du etwas gegen ihn in der Hand haben –
etwas, was für deinen Gegenspieler so verlockend ist, dass er im Gegenzug etwas für dich tun will.
Das könnte etwas sein, was er unbedingt in seinen Besitz bringen will oder etwas, von dem er unbedingt vermeiden will, dass du es tust.
Wie einen Sack voll Gold.
Oder einen Schlag ins Gesicht.
Was als Druckmittel in Frage kommt, hängt von den beteiligten Parteien und der gestellten Forderung ab.
Drohe einem einzelnen Goblin mit dem Tod und du hast etwas gegen ihn in der Hand.
Drohe einem Goblin, der seinen ganzen Stamm als Unterstützung hinter sich hat, mit dem Tod, und er wird sich überlegen, ob er mit einem Kampf besser davonkommt.

Bei einer 7+ wirst du nach einem Versprechen gefragt, das mit deinem Druckmittel zusammenhängt.
Wenn dein Druckmittel beispielsweise darin besteht, dass du vor deinem Gegenspieler stehst, dein Messer schärfst und andeutest, wie sehr du Lust hast, ihn aufzuschlitzen, dann wird er dich möglicherweise anflehen, ihn gehen zu lassen.
Wenn dein Druckmittel deine einflussreiche Stellung am Hofe des Königs ist, könnte dein Gegenspieler dich vielleicht um einen Gefallen bitten.

Was dabei auch immer von dir verlangt wird, bei einer 10+ musst du es klar und deutlich versprechen.
Bei einer 7–9 reicht das noch nicht aus:
Bevor dein Gegenspieler tut, was du von ihm verlangst, musst du sofort einen Beweis dafür liefern, dass du dein Versprechen in die Tat umsetzen wirst.
Angenommen, du bietest einem Händler Schutz vor den Wölfen, wenn er im Gegenzug tut, was du verlangst.
Wenn du dann eine 7–9 würfelst, wird er seinen Teil des Abkommens erst erfüllen, wenn du ihm einen frischen Wolfspelz bringst – als Beweis dafür, dass du überhaupt dazu in der Lage bist.
Ein interessanter Punkt ist, dass du dein Versprechen überhaupt nicht in die Tat umsetzen musst;
ob du es tust oder nicht, hängt ganz von dir ab.
Natürlich können gebrochene Versprechen zu späteren Schwierigkeiten führen.
Wenn du als Eidbrecher bekannt bist, wird man mit dir nicht eben freundlich umgehen und du kannst dich darauf einstellen, dass dir des Öfteren die kalte Schulter gezeigt wird.

Manchmal ist das Versprechen, das du deinem Gegenspieler machen musst, bereits in deinem Verhandlungsziel inbegriffen – so wie in "Verschwinde und ich verspreche dir, dich am Leben zu lassen".
Es hängt ganz vom Gegenspieler ab, ob er mit diesem Versprechen leben kann oder etwas ganz anderes im Sinn hat.
Er könnte antworten "Ja, lass mich leben und ich werde mich nie wieder hier blicken lassen" (mit entsprechender Absicherung, wenn du eine 7–9 gewürfelt hast) oder er könnte stattdessen erwidern "Versprich mir erst, dass du mir nicht folgen wirst".

____
Leena: Lord Hywn, ihr müsst euch für mich verbürgen oder die Königin wird mir nie eine Audienz gewähren.

SL: Er ist nicht wirklich überzeugt; wenn du ihn blamierst, könnte das seinem Ruf empfindlichen Schaden zufügen.
"Warum sollte ich euch helfen, Leena?"

Leena: Oh, während ich mit ihm spreche, spiele ich beiläufig mit dem Siegelring dieses Mörders, den wir getötet haben.
Des Mörders, den er auf den Prinzen angesetzt hatte.
Ich stelle sicher, dass der Lord den Ring auch sieht.

SL: Oha, na gut.
Würfle _Schachern_.

Leena: Eine 8.

SL: "Genug der Scherereien!", ruft er mit eisiger Wut.
"Wir wissen beide, dass ihr meinen gedungenen Mann ermordet habt.
Gebt mir den Ring, schwört mir, dass kein Wörtchen darüber eure Lippen verlässt, und ich tue, was ihr sagt."

Leena: Ich werfe ihm den Ring hin.
Das wird sicher nicht der einzige Dreck sein, den dieser Mistkerl am Stecken hat.
____
____
Pendrell: Hier spielt Einauge immer Karten, nicht wahr?
Gut, ich schlendere hinüber zu den Türstehern.
"Hey Leute, wie wär's, wenn ihr, na ja… die Tür aufmacht und mich reinlasst?"
Und ich bin dabei charmant und cool und so.
_Schachern_ ist würfeln+CHA, nicht wahr?

SL: Nicht so schnell, du gerissener Hund.
Du hast bist jetzt nur gesagt, was du eigentlich willst.
Der Große auf der rechten Seite, der streng riecht, baut sich vor dir auf und sagt gelangweilt "Bitte um Verzeihung, Sir, geschlossene Gesellschaft."
Er wirkt, als hasse er seinen Job und wünschte, er wäre woanders.
Wenn du _schachern_ willst, brauchst du eine Art von Druckmittel.
Vielleicht hilft ein bisschen Schmiere?
____

.Helfen oder Hindern
****
*Wenn du jemanden unterstützen oder von etwas abhalten willst,* würfle+Bande.
✴ Bei einer 10+ bekommt er +1 oder -2 auf seinen Wurf, ganz wie du willst.
✴ Bei einer 7–9 bekommt er +1 oder -2, aber du setzt dich dabei seiner Vergeltung oder einer anderen Gefahr aus, oder dein Eingreifen hat einen Preis.
****

Wann immer du das Gefühl hast, dass Spieler gegeneinander würfeln sollten, sollte der Verteidiger den Angreifer _behindern_.
Das muss nicht immer bedeuten, dass er ihn und seine Pläne sabotieren will.
_Helfen oder Hindern_ kann zum Beispiel auch angewandt werden, um gegen _Schachern_ zu argumentieren, oder wenn du dich als schwer durchschaubarer, gerissener Bursche inszenieren willst.
Letzten Endes geht es darum, dass du einem anderen Spieler Steine in den Weg legen willst.

Frage immer, auf welche Art und Weise der Spieler seinem Ziel _helfen_ oder es _behindern_ möchte.
Solange er das beantworten kann, löst er den Zug aus.
Manchmal musst du als SL auch nachfragen, ob eine Einmischung stattfindet; es könnte sein, dass deine Spieler übersehen, wenn sie gegen- oder miteinander arbeiten.

_Helfen_ ist etwas offensichtlicher.
Solange ein Spieler erklären kann, auf welche Art und Weise er bei einem Zug helfen will und die Erklärung Sinn macht, gestatte ihm seinen _Helfen_-Wurf.

Es ist egal, wie viele Leute sich in einen Wurf einmischen; das Ziel bekommt den +1-Bonus/-2-Malus nur einmal.
Selbst wenn eine ganze Gruppe Abenteurer auf einmal ihrem Krieger helfen, den Oger anzugreifen, bekommt dieser letzten Endes trotzdem nur +1.

____
SL: Ozruk, du stehst einsam und blutverschmiert vor einem Pack aufgebrachter Höllenhunde.
Hinter dir kauert der Prinz von Lescia, und er weint in seiner Todesangst.

Ozruk: Ich wappne mich und hebe meinen Schild.
Ich werde meine Pflicht tun und den kleinen Prinzen verteidigen, und wenn es das letzte ist, was ich tue.

Aronwe: Ich trete aus dem Schatten und ziehe mein Schwert!
"Noch sind wir nicht geschlagen, Zwerg!"
Ich stehe ihm bei und will ihm beim _Verteidigen_ _helfen_.
"Wir mögen Fremde sein, aber ich habe euch kämpfen sehen, Ozruk.
Wenn wir heute sterben, dann als Brüder in der Schlacht!"
Ich habe keine Bande mit ihm, aber ich will es trotzdem versuchen.

SL: Das war wirklich bewegend.
Okay, würfle+0.
Wenn der Wurf erfolgreich ist, bekommst du, Ozruk, +1 auf deinen _Verteidigen_-Wurf.
Los geht's!
____

== Spezielle Züge

Spezielle Züge sind solche, die im Spielverlauf weniger häufig oder nur in bestimmten Situationen auftreten.
Trotzdem sind sie ein grundlegender Teil aller Dinge, die Spielercharaktere in _Dungeon World_ tun können – insbesondere dann, wenn sie nicht gerade zu epischen Abenteuern ausgezogen oder in Verliesen unterwegs sind.

.Letzter Atemzug
****
*Wenn du stirbst,* kannst du einen Blick auf das erhaschen, was jenseits des schwarzen Tores liegt.
Der SL wird es dir beschreiben.
Würfle+nichts – den Tod interessiert es nicht, wie hart oder abgebrüht du bist.
✴ Bei einer 10+ springst du dem Tod von der Schippe:
Dein Leben hängt am seidenen Faden, aber du bist am Leben.
✴ Bei einer 7–9 wird dir der Tod einen Handel vorschlagen.
Wenn du ihn annimmst, stabilisiert sich dein Zustand.
Wenn nicht, trittst du die Reise jenseits des schwarzen Tores an, dem Schicksal entgegen, das dich dort erwarten mag.
✴ Bei einer 6- ist dein Schicksal besiegelt;
der Tod hat dich als einen der Seinigen markiert und wird dich bald über die Schwelle geleiten.
Der SL wird dir sagen, wann.
****

Dein _letzter Atemzug_ ist jener Moment, in dem du an der Schwelle zwischen Leben und Ableben stehst.
Die Zeit steht still, während der Tod dich zu sich holt.
Auch wenn du nicht durch das schwarze Tor schreitest, kannst du einen Blick auf das erhaschen, was dich dahinter erwartet – alte Freunde und alte Feinde, Lohn oder Strafe für vergangene und zukünftige Taten, oder noch seltsamere Ausblicke können sich darbieten.
Dieser Moment verändert jeden, der ihn erlebt – auch die, die ihm entrinnen können.

Der Zug kann drei Auswirkungen haben.
Bei einer 10+ hast du den Tod auf bedeutsame Weise übertrumpft und bist mit etwas davongekommen, das nicht mehr rechtmäßig dir gehört.
Der Tod hat keine Macht, das aufzuhalten, aber er wird die Kränkung nicht vergessen.
Bei einer 7–9 sollte der SL dich vor eine Wahl mit erheblichen Konsequenzen stellen.
Für den SL:
Behalte dabei im Hinterkopf, wie der Charakter sich im Spiel verhalten hat und was du während des Spiels über ihn gelernt hast.
Der Tod weiß alles und sieht alles, dementsprechend wird er sein Angebot gestalten.
Denke daran – dies ist ein Handel.
Biete etwas, das eine Herausforderung für den Spieler darstellt und das Spiel gleichzeitig in eine interessante neue Richtung führt.
Bei einem Fehlschlag ist der Tod unausweichlich.
Das Naheliegende wäre, zu sagen "Der Tod geleitet dich über die Schwelle, in sein finsteres Königreich" und weiterzumachen.
Manchmal kommt der Tod allerdings schleichend.
Du könntest sagen "Du hast noch eine Woche zu leben" oder "Du spürst die kalte Hand des Todes auf deiner Schulter" und es zunächst dabei belassen.
Wenn der Spieler an diesem Punkt nachgibt und sich in sein Schicksal fügt, dann ist das vollkommen in Ordnung.
Stelle mit ihm einen neuen Charakter zusammen wie sonst auch.
Das Wesentliche, was du dir merken musst, ist, dass eine Berührung mit dem Tod einen schicksalhaften Moment darstellt, der an niemandem spurlos vorüberzieht.

____
SL: Sparrow, als die Messerklinge in deinen Eingeweiden verschwindet, schwindet die Welt mit ihr.
Du stehst vor den Schwarzen Toren des Todes.
In der Schar der leidenden Seelen erspähst du Lord Hwyn, diesen widerlichen Hundesohn.
Es scheint, als hätten ihn seine kranken Machenschaften endlich eingeholt.
Eure Augen kreuzen sich über der schwarzen Schlucht, und du kannst seinen Hunger bis tief in deine Seele spüren.
Nimm deinen letzten Atemzug.

Sparrow: Heftig.
Ich habe eine 9.

SL: Der Tod erscheint vor dir, Fetzen schwarzen Stoffes tanzen um seine schemenhafte Gestalt.
Eine bleiche Hand streicht über dein Gesicht.
Du vernimmst seine Stimme in deinem Kopf.
"So früh schon bist du bei mir, kleiner Spatz?
Du folgst dem Fluss der Seelen, hierhergeschwemmt von deiner Klinge.
Ich habe dich dafür sehr liebgewonnen.
Du sollst zurückkehren in deine Welt, aber versprich mir dies:
So, wie du im Schatten verweilst, sollst du Teil des Schattens werden.
Meide das Licht der Sonne für immer, oder beehre mich wieder.
Wie lautet deine Antwort, kleine Diebin?"

Sparrow: (schluck)
____

.Belastung
****
*Wenn du einen Zug auslöst, während du Gewicht mit dir herumträgst,* kann sich diese Belastung nachteilig auswirken.
Wenn du…

* maximal deine Traglast mit dir trägst, erhältst du keinen Malus.
* bis zu deiner Traglast+2 mit dir trägst, erhältst du -1 fortlaufend, bis du dich von deiner Last befreist.
* mehr als deine Traglast+2 mit dir trägst, hast du die Wahl: Lasse etwas mit einem Gewicht von 1 oder mehr fallen oder dein Wurf schlägt automatisch fehl.
****

Die Traglast eines Charakters wird durch seine Klasse und STÄ bestimmt.
Mehr tragen zu können ist ein deutlicher Vorteil, wenn du Schätze aus einem Verlies schleppst – oder wenn du versuchst, genug Ausrüstung mitzubringen, um auf alles gefasst zu sein.

Dieser Zug trifft nur auf Gegenstände zu, mit denen du normal herumlaufen und trotzdem noch agieren kannst.
Einen großen Felsbrocken auf dem Rücken zu tragen ist keine _Belastung_, weil du dich damit nicht in der Lage bist, dich vernünftig zu bewegen oder andere Handlungen durchzuführen.
Stattdessen beeinflusst es, welche Züge du in der Fiktion auslösen kannst.

.Lager aufschlagen
****
*Wenn du dich zur Ruhe niederlässt,* verbrauche eine Ration.
Wenn du an einem gefährlichen Ort rastest, lege außerdem die Wachen fest.
Falls du genügend EP hast, darfst du eine Stufe aufsteigen.
Solange du wenigstens ein paar Stunden durchgehend schlafen konntest, heile die Hälfte deiner maximalen Trefferpunkte an Schaden.
****

Du schlägst dein Lager normalerweise auf, um anderen Tätigkeiten nachzugehen – Zaubersprüche lernen beispielsweise, oder zu deinem Gott beten.
Oder, du weißt schon, ausschlafen.
Wann immer du für eine oder zwei Stunden anhältst, um zu Atem zu kommen, _schlägst_ du wahrscheinlich dein _Lager auf_.

Du _schlägst_ auch dann dein _Lager auf_, wenn du in einem Gasthaus oder Herberge unterkommst.
Du heilst ganz normal Trefferpunkte, aber deine Rationen verbrauchst du nur dann, wenn du sie von dem Essen nimmst, das du selbst mitgebracht hast – nicht, wenn du für dein Essen bezahlt hast oder umsonst bewirtet wurdest.

.Wache halten
****
*Wenn du Wachdienst hast und sich etwas dem Lager nähert,* würfle+WEI.
✴ Bei einer 10+ gelingt es dir, das Lager zu wecken und bereitzumachen; jeder im Lager erhält +1 voraus.
✴ Bei einer 7–9 hast du einen Moment zu spät reagiert:
Deine Gefährten sind wach, aber sie hatten keine Zeit, sich vorzubereiten.
Sie haben nichts außer ihrer Waffen und Rüstungen.
✴ Bei einer 6- ist das, was auch immer im Dunkeln lauert, euch gegenüber im Vorteil.
****
