
== Grundlegende Moves

Dieses Kapitel enthält Moves, die allen Charakteren zur Verfügung stehen.
Sie lassen sich in zwei Kategorien unterteilen: Grundlegende und spezielle.

Grundlegende Moves machen den Löwenanteil des Abenteurerlebens aus.
Sie kommen zur Anwendung in Kämpfen, angespannten Verhandlungen, gefährlichen Gegenden und dergleichen.

Spezielle Moves werden seltener zum Einsatz kommen.
Sie behandeln Sachen wie Stufenaufstiege, das Unternehmen einer langen Reise oder die Rückkehr in die Stadt nach einem Abenteuer.

Alle Spielercharaktere können grundlegende und spezielle Moves benutzen.
Zusätzlich hat jeder Spielercharakter Moves, die ihm von seiner Klasse zur Verfügung gestellt werden – die werden wir uns später genauer anschauen.

Wir werden jeden Move zuerst beim Namen nennen, danach folgt eine Beschreibung seiner Regeln.
Einige Moves werden begleitet von einer kurzen Erläuterung ihrer Nutzung und einem Spielbeispiel.

=== Grundlegende Moves

.Hauen und Stechen
****
*Wenn du einen Gegner im Nahkampf angreifst,* würfle+STÄ.
✴ Bei einer 10+ fügst du deinem Gegner Schaden zu und entrinnst seinem Angriff.
Wenn du willst, kannst du außerdem +1W6 Schaden machen, setzt dich dabei aber dem Angriff deines Gegners aus.
✴ Bei einer 7–9 fügst du deinem Gegner Schaden zu und dein Gegner kann einen Angriff gegen dich ausführen.
****

_Hauen und Stechen_ ist dazu da, einen wehrhaften Feind anzugreifen – schlicht und einfach.
Wenn dein Gegner sich nicht wehren kann – weil er nicht weiß, dass du da bist, oder weil er gefesselt und hilflos ist –, dann ist das kein _Hauen und Stechen_.
Du machst einfach deinen Schaden oder tötest ihn sofort, je nachdem, was die Situation gerade hergibt.
Böse Sache.

Der Angriff deines Gegners kann ein beliebiger Spielleiter-Move sein, solange er direkt von diesem Gegner ausgeht.
Ein Goblin schlägt vielleicht einfach zurück, oder er rammt dir eine vergiftete Nadel in die Seite.
Das Leben als Abenteurer ist nunmal kein Zuckerschlecken.

Beachte, dass ein "Angriff" eine Aktion eines Spielers beinhaltet, die dazu führen kann, dass jemand (oder etwas) anderes Schaden erleidet.
Ein Schwert gegen einen Drachen zu schwingen, dessen zentimeterdicke Schuppen mit magischer Energie vollgepumpt sind, lässt sich vergleichen mit dem Schwingen eines Fleischerbeils gegen einen Panzer:
Es wird ihm einfach keinen Schaden zufügen, also ist _Hauen und Stechen_ hier nicht anwendbar.
Das kann sich jedoch ändern, wenn die Umstände anders sind:
Wenn du so positioniert bist, dass du den weichen Bauch des Drachen angreifen kannst (viel Glück beim Dahinkommen!), kannst du ihm wehtun, und das ist dann ein Angriff.

Wenn es Sinn macht, dass du mit der Aktion, die den Move ausgelöst hat, mehrere Feinde angreifen kannst, würfle einmal und füge jedem Ziel den Schaden zu (abzüglich seiner Rüstung).

Manche Angriffe können – abhängig von der auslösenden Aktion, den Umständen oder den eingesetzten Waffen – zusätzliche Effekte haben:
Ein Angriff könnte jemanden niederschlagen, oder entwaffnen… oder nichts außer einem großen, blutigen Fleck hinterlassen.

____
SL: Jarl, du steckst bis zum Hals in geifernden Goblins.
Sie haben dich umzingelt und ihre Messer gezückt.
Was machst du?

Jarl: Mir reicht’s!
Ich verdresche den nächstbesten Goblin mit meinem Hammer.

SL: Okay.
Das ist eine Kampfsituation, also benutzt du Hauen und Stechen.
Würfle+STÄ.

Jarl: Eine 11.
Die Regeln sagen mir, dass ich eine Wahl treffen muss.
Furcht ist was für Schwächlinge, also lass diese Goblins nur kommen!

SL: Du lässt deinen Hammer in den nächstbesten Goblin krachen.
Deine Belohnung ist das befriedigende Geräusch seiner brechenden Knochen – das und eine Messerwunde, die du von seinem Gegenangriff bekommst.
Er richtet 4 Schadenspunkte bei dir an.
Was machst du?
____

____
SL: Cadeus, aus den Schatten kannst du diese Ork-Krieger überraschen.
Cadeus: Ich springe hervor lasse mein Schwert in hohem Bogen auf sie herabsausen.
Etwa so!
Yaaaah!

SL: Das hatten sie nicht erwartet, du hast sie komplett auf dem falschen Fuß erwischt und versenkst dein Schwert in einem von ihnen.
Würfle deinen Schaden.

Cadeus: Ich mache 6 Schaden.

SL: Der Ork fällt blutend zu Boden!
Der zweite stockt kurz, als er dich sieht.
Dann grinst er dich an, entblößt dabei seine widerlichen Hauer, und löst sein Signalhorn vom Gürtel!
Was machst du?
____

____
SL: Bartleby, du hast Finbar den Prächtigen, mächtigsten Duellanten des Landes, komplett entwaffnet und legst deine Klinge an seinem Hals.

Bartleby: Du wirst mich nicht noch einmal hintergehen, Finbar! Ich durchbohre ihn mit dem Schwert.

SL: Na gut, das ist dann Hauen und Stechen. Würfle+STÄ.

Bartleby: Na gut, wenn du das sagst… Ich habe eine 7.

SL: Okay, du durchbohrst ihn, weil er komplett wehrlos ist und… ähm, warte.
Weißt du was, er befindet sich gar nicht im Nahkampf mit dir.
Er ist hilflos, vergiss Hauen und Stechen, er ist erledigt.
Er sackt Blut spuckend zu Boden, aber der Alarm der Wache dringt in deine Ohren.
Was machst du?
____

.Salve
****
*Wenn du zielst und im Fernkampf auf einen Gegner schießt,* würfle+GES.
✴ Bei einer 10+ hast du ein freies Schussfeld – mache deinen Schaden.
✴ Bei einer 7–9, wähle eins (egal, was du wählst, du richtest deinen Schaden an):

* Du musst dich bewegen, um deinen Schuss anbringen zu können, und begibst dich dadurch in Gefahr (vom SL vorgegeben)
* Du musst nehmen, was du kriegen kannst: -1W6 Schaden
* Du musst mehrere Salven abfeuern: Reduziere deine Munition um 1
****

Eine _Salve_ beinhaltet den gesamten Akt des Spannens, Zielens und Feuerns einer Fernkampfwaffe, oder das Werfen einer Wurfwaffe.
Der Vorteil gegenüber dem Nahkampf besteht darin, dass der Angegriffene weniger Chancen hat, zurückzuschlagen.
Im Gegenzug muss ein Fernkämpfer auf seine Munition und ein freies Schussfeld achten.
