== Helfen

Zunächst einmal vielen herzlichen Dank für deine Hilfe!
Um "Kleinarbeit" für alle Beteiligten zu vermeiden, beachte bitte ein paar Punkte, wenn du bei der Übersetzung helfen willst.

=== Fließtext

Bitte fange für jeden Satz eine neue Zeile an.
Dies dient dazu, die Erkennung von geänderten Satzteilen in Diffs zu erleichtern.

Wenn du Eigennamen von Regelkonstrukten (in erster Linie die Namen von Zügen oder Beeinträchtigungen) im Fließtext benutzt, umgebe sie bitte `_mit Unterstrichen_`, damit sie kursiv gerendert werden und als dedizierte Regeln wahrgenommen werden.
Ein paar Beispiele dafür kannst du in den https://github.com/runiq/dungeon-world-deutsch/blob/master/ch4.asciidoc#grundlegende-züge-1[Erläuterungen zu _Hauen und Stechen_] finden.

=== Überschriften

Überschriften sollten mit Ebene 2 anfangen (`==`); Ebene 1 ist in Asciidoc dem Dokumenttitel vorbehalten.
Das "Überspringen" von Überschriftenebenen (z.B. `====` direkt nach `==`) ist in Asciidoc ebenfalls nicht erlaubt.
Ansonsten gehe einfach so vor wie im http://book.dwgazetteer.com[Quelldokument] angegeben – wenn dort Überschriften übersprungen werden, mach einfach, wie du es für richtig hältst.

=== Züge

Die Beschreibungen von Zügen werden folgendermaßen gebaut:

----
*Flimmen und Flommen*

'''
*Wenn du XXX YYY,* würfle+BLA.
✴ Bei einer 10+, flimme dies.
✴ Bei einer 7–9, flomme das.

'''
----

Daraus wird dann:

*Flimmen und Flommen*

'''
*Wenn du XXX YYY,* würfle+BLA.
✴ Bei einer 10+, flimme dies.
✴ Bei einer 7–9, flomme das.

'''

Beachte dabei Folgendes:

* Der Name des Zuges sollte fett sein.
Eine Überschrift hat sich an der Stelle nicht bewährt.
* Die Bedingung, unter der der Zug ausgelöst wird, sollte ebenfalls fett sein, damit sie auf den ersten Blick ersichtlich ist.
* Die Sterne vor den einzelnen Punkten sind keine echten Aufzählungszeichen (`*` am Zeilenanfang werden in Asciidoc als Aufzählungen gerendert), sondern achtzackige Sterne (Unicode: http://unicode-table.com/de/2734[_eight pointed black star_]).
Das sind dieselben Zeichen, die auch im Originaltext verwendet werden.
* Vor den horizontalen Linien (`'''`) bitte eine Leerzeile lassen, weil die Linien sonst nicht gerendert werden.
