== Der Barde
 
In Gedichten wird das Leben eines Abenteurers als eine offene Straße voller Ruhm, Münzen und Kampf beschrieben.
Die Sagen die in jeder mit Bauern gefüllten Taverne erzählt werden, müssen doch ein Körnchen Wahrheit in sich haben nicht wahr?
Die Lieder welche Bauern und Könige zugleich Inspirieren, wilde Bestien beruhigen oder Männer in die Raserei treiben, müssen von irgendwo her kommen.

Einführung des Barden.

Ihr, mit eurer geschmeidigen Zunge und Schlagfertigkeit.
Ihr Geschichtenerzähler und Liedermacher.
Es braucht bloß einen einfachen Minnesänger für eine Erzählung aber einen wahren Barden sie nachzuleben.
Macht euch bereit, ihr edlen Redner.
Schärft eure versteckten Dolche und erhört den Ruf.
Jemand muss Schulter an Schulter mit Schlägern, Verbrechern und baldigen Helden kämpfen. 
Und wer ist besser geeignet die Geschichte eures Heldenmutes zu schreiben als Ihr selbst? 
Niemand.
Los geht’s.

=== Namen

_Elf:_ Astrafel, Daelwyn, Feliana, Damarra, Sistranalle, Pendrell, Melliandre, Dagoliir

_Mensch:_ Baldric, Leena, Dunwick, Willem, Edwyn, Florian, Seraphine, Quorra, Charlotte, Lily, Ramonde, Cassandra

=== Aussehen

Wähle von jeden eins.

Wissende Augen, Feurige Augen, Freudige Augen 

Ausgefallenes Harr, Wildes Harr, Stilvolle Kappe 

Prachtvolle Kleidung, Reisekleidung, Lumpen

Gutgebauter Körper, Wohlgenährter Körper, Magerer Körper

=== Attribute

maximale TP sind 6+Konstitution

Dein Basisschaden ist W6

=== Anfangszüge

*Wähle eine Rasse mit den folgenden Fähigkeiten.*

*Elf*

'''
*Wenn du eine wichtige/s Gegend/Gebäude betrittst,* kannst du den SL nach einen historischen Fakt zu dieser Gegend/Gebäude fragen.

'''

*Mensch*

'''
*Wenn du eine zivilisierte Siedlung zum ersten mal betrittst,* wird jemand, der den Brauch der Gastfreundlichkeit gegenüber Barden respektiert, dich als sein Gast einladen.

'''

*Du beginnst das Spiel mit den folgenden Zügen:*

*Zauberei Künste*

'''
*Wenn du eine Aufführung zu einen Zauber webst,* dann wähle einen Verbündeten und eine Wirkung.

* Heile 1W8 Schaden
* +1W4 zusätzlichen Schaden
* Der Geist wird von einem Zustand befreit
* Das nächste Mal wenn jemand dem Ziel erfolgreich hilft bekommte er/sie +2 statt +1

Dann würfel+Cha.

✴ Bei einer 10+ erhält der Verbündete den gewählten Effekt.
✴ Bei einer 7–9, wirkt der Zauber weiterhin aber du ziehst ungewollte Aufmerksamkeit auf dich oder der Zauber wirkt auch auf andere Ziele.
Wahl des SL.

'''

*Barden Wissen*

'''
Wähle einen Kenntnis Bereich:

* Zauber und Magie
* Die Toten und Untoten
* Die großen Geschichten der bekannten Welt
* Bestiarium der Ungewöhnlichen Kreaturen
* Die Planar Sphäre
* Legenden vergangener Helden
* Götter und Ihre Diener

*Wenn du zum ersten Mal einer/n wichtigen/r Kreatur, Ort oder Gegenstand begegnest/findest das von deinen Barden Wissen abgedeckt ist,* kannst du dem SL jede beliebige Frage dazu stellen.
Der SL muss wahrheitsgemäß Antworten.
Er darf dich jedoch Fragen in welcher Sage, Geschichte oder Legende du davon gehört hast.

'''

*Charmant und Offen*

'''
*Wenn du geradeheraus mit jemanden sprichst,* kannst du seinen/ihren Spieler eine Frage aus der unteren Liste stellen.
Er/Sie muss wahrheitsgemäß antworten, dann können sie dir eine Frage aus der Liste stellen die du wiederum wahrheitsgemäß beantworten musst.

* Für wen arbeitest du?
* Was wünschst du soll ich tun?
* Wie bekomme ich dich zu pass:[____________]?
* Was fühlst du wirklich gerade?
* Wonach verzehrst du dich am meisten?

'''

*Ein Hafen im Sturm*

'''
*Wenn du zu einer zivilisierten Siedlung zurückkehrst die du bereits besucht hast,* dann sag dem SL wann du das letzte Mal hier warst.
Er erzählt dir dann was sich seitdem verändert hat.

'''

=== Gesinnung 

*Wähle eine Gesinnung.*

==== Gut

Nutze deine Kunst um anderen zu helfen

==== Neutral

Vermeide Konflikte oder angespannte Situationen

==== Chaotisch

Sporne andere zu bedeutenden und ungeplanten aber ausschlaggebenden Aktionen an

=== Ausrüstung

Deine Tragkraft beträgt 9+STR.
Du hast Verlies Rationen (5 Benutzungen, 1 Gewicht).
Wähle ein Instrument, alle haben 0 Gewicht für dich.

* Die Mandoline deines Vaters, repariert.
* Eine feine Laute, ein Geschenk von einem Adligen.
* Die Flöte, mit dem du deine erste Liebe umworben hast.
* Ein gestohlenes Horn.
* Eine Geige, noch nie gespielt 
* Ein Gesangbuch in einer vergessenen Sprache

Wähle deine Kleidung

* Lederrüstung (1 Rüstung, 1 Gewicht)
* Protzige Kleider (0 Gewicht)

Wähle deine Waffen

* Duell Rapier (nah, stechen, 2 Gewicht)
* Abgenutzter Bogen (nah, 2 Gewicht) Bündel Pfeile (3 Munition, 1 Gewicht), und Kurzschwert (nah, 1 Gewicht)

Wähle eins

* Abenteurer Ausrüstung (1 Gewicht)
* Bandagen (0 Gewicht)
* Halbling Pfeifentabak
* 3 Münzen

=== Bande

Trage den Namen von einen deiner Begleiter in mindestens einen der Felder ein.

Dies ist nicht mein erstes Abenteurer mit pass:[____________].

Ich habe Lieder über pass:[____________] gesungen lange bevor ich ihn traf.

pass:[____________] ist oft Ziel meiner Witze.

Ich schreibe eine Ballade über die Abenteuer von pass:[____________].

pass:[____________] hat mir ein Geheimnis anvertraut.

pass:[____________] vertraut mir aus guten Grund nicht.

=== Erweiterte Züge

*Wenn du eine Stufe von 2–5 erreichst, dann wähle von folgenden Zügen:*

*Heilendes Lied*

'''
*Wenn du mit _arkaner Kunst_ heilst,* dann heilst du +1W8 Schaden.

'''

*Grauenhafte Kakophonie*

'''
*Wenn Du Bonusschaden mit _arkanen Kunst_ gewährst bekommst,* gibt es zusätzlichen +1W4 Schaden.

'''

*Es geht bis elf*

'''
*Wenn du einen wahnsinnigen Auftritt hinlegst (ein Flöten Solo),* wähle ein Ziel das dich hören kann und würfle+CHA.
✴ Bei einer 10+ greift das Ziel seinen nächsten Verbündeten in Reichweite an.
✴ Bei einer 7–9 greift das Ziel seinen nächsten Verbündeten an, aber du ziehst auch seine/ihre Aufmerksamkeit und seine/ihre Wut auf dich.

'''

*Kreischendes Metall*

'''
*Wenn du laut schreist oder eine erschütternde Melodie spielst,* wählst du ein Ziel.
Würfle+KON.
✴ Bei einer 10+ nimmt das Ziel 1W10 Schaden und ist für ein paar Minuten benommen.
✴ Bei einer 7–9 fügst du zwar noch Schaden aber die Sache gerät außer Kontrolle. 
Der SL wählt ein zusätzliches Ziel in der Nähe.

'''

*Ein wenig Hilfe von meinen Freunden*

'''
*Wenn du jemanden erfolgreich _hilfst_,* bekommst du ebenfalls +1 voraus.

'''

*Komischer Klang*

'''
Die _arkane Kunst_ in dir ist stark, was dir erlaubt 2 Effekte anstatt 1 zu Wählen

'''

*Duellanten Parade*

'''
*Beim _Hauen und Stechen_* bekommst du +1 Rüstung voraus.

'''

*Betrügen*

'''
*Wenn du mit jemanden _schacherst_,* bekommst du bei einer 7+ zusätzlich +1 voraus.

'''

*Amateur der Klassen*

'''
Erhalte einen Zug von einer anderen Klasse.
Behandle deine Stufe als 1 tiefer für den gewählten Zug.

'''
*Wenn du eine Stufe zwischen 6–10 hast wähle diese, oder von den Stufe 2–5 Zügen.*

*Heilender Chor*

'''
Ersetzt _Heilendes Lied_

*Wenn du mit _arkaner Kunst_ heilst,* heilst du +2W8 Schaden.

'''

*Grauenhafte Explosion*

'''
Ersetzt _Grauenhafte Kakophonie_

*Wenn Du Bonusschaden mit _arkaner Kunst_ gewährst bekommst,* gibt es zusätzlichen +2W4 Schaden.

'''

*Unvergessliches Gesicht*

'''
*Wenn du jemanden nach einiger Zeit wiedertriffst (deine Entscheidung),* bekommst du +1 voraus.

'''

*Reputation*

'''
*Wenn du zum ersten mal jemanden triffst der Lieder über dich gehört hat,* würle+CHA.
✴ Bei einer 10+ sage dem SL 2 dinge die er über dich gehört hat.
✴ Bei einer 7–9, erzählst du dem SL eine Sache die Er über dich gehört hat und der SL die 2te. 

'''

*Komische Akkorde*

'''
Ersetzt: _Komischer Klang_

*Wenn du _Arkane Kunst_ benutzt,* kannst du 2 Effekte wählen.
Du kannst außerdem einen der Effekte verdoppeln.

'''

*Ein Gehör für Magie*

'''
*Wenn du hörst dass ein Gegner Magie wirkt,* dann wird SL dir den Namen des Zauber sagen und seine Effekte.
Nimm +1 voraus wärend du dagegen handelst.

'''

*Verschlagen*

'''
*Wenn du _Charmant und Offen_ benutzt,* kannst du ebenfalls fragen: „Wie sind Sie anfällig für mich?“
Der Gefragte wird diese Frage nicht an dich zurückstellen. 

*Duellanten Block*

'''
Ersetzt _Duellanten Parade_

*Bei _Hauen und Stechen_* bekommst du +2 Rüstung voraus.

'''

*Con*

'''
Ersetzt: _Betrügen_

*Wenn du mit jemanden verhandelst,* bekommst du bei einer 7+ zusätzlich +1 voraus.
Der Verhandlungspartner muss außerdem eine Frage wahrheitsgemäß beantworten.

'''

*Meister der Klassen*

'''
Wähle ein Zug von einer anderen Klasse.
Behandle deine Stufe als eins niedriger.

'''
