== Der Kleriker

Die Länder von Dungeon World sind ein von den Götter verlassenen Chaos.
Sie sind lausig, mit Untoten übersäht, zahlreichen Monstern und weiten unnatürlichen Ebenen zwischen sicheren und gesegneten Zivilisationen.
Es ist eine Gottlose Welt da Draußen.
Und deshalb braucht sie Dich.
Den Heiden die Herrlichkeit deines Gottes zu bringen, ist nicht nur deine Natur, es ist deine Bestimmung.
Es liegt dabei bei dir ob sie mit Schwert, Streitkolben oder Zauber bekehrt werden.
Sich tief in das Ruchlose Herz der Wildnis zu schlagen um dort den Samen der Göttlichkeit zu pflanzen.
Ein Mancher sagt es sei das beste, Gott in seinen Herzen zu tragen. Aber ihr wisst es besser.
Gott lebt am Ende einer Klinge.

Zeigt der Welt wer ihr Meister ist.

=== Namen

Zwerg: Durga, Aelfar, Gerda, Rurgosh, Bjorn, Drummond, Helga, siggrun, Freya
Mensch: Wesley, Brinton, Jon, Sara; Hawthron, Elise, Clarke, Lenore, Piotr, Dahlia, Carmine

=== Aussehen

Wähle von Jeden eins:
Freundlichen Augen, scharfe Augen oder Traurige Augen
Tonsur, wildes Haar oder Glatze
Wallenden Gewändern, Mönchsgewand, oder Gewöhnliches Gewand 

Dünnen Körper, Knorriger Körper oder Schwabeliger Körper 

=== Attribute

Deine maximalen TP sind 8+ KON
Grundschaden ist W6

=== Anfangs Züge

Wähle eine Rasse um die Zugehörigen Züge zu erhalten.

==== Zwerg
Du bist eins mit den Stein.
Wenn du dich Unterhältst, dann lernst du eine spezielle Art der Wörter des Ungesprochenen, welche nur die Steine kennen.

==== Mensch

Dein Glaube ist vielfältig.
