== Der Kleriker

Die Länder von Dungeon World sind ein von den Götter verlassenen Chaos.
Sie sind lausig, mit Untoten übersäht, zahlreichen Monstern und weiten unnatürlichen Ebenen zwischen sicheren und gesegneten Zivilisationen.
Es ist eine Gottlose Welt da Draußen.
Und deshalb braucht sie Dich.
Den Heiden die Herrlichkeit deines Gottes zu bringen, ist nicht nur deine Natur, es ist deine Bestimmung.
Es liegt dabei bei dir ob sie mit Schwert, Streitkolben oder Zauber bekehrt werden.
Sich tief in das Ruchlose Herz der Wildnis zu schlagen um dort den Samen der Göttlichkeit zu pflanzen.
Ein Mancher sagt es sei das beste, Gott in seinen Herzen zu tragen. Aber ihr wisst es besser.
Gott lebt am Ende einer Klinge.

Zeigt der Welt wer ihr Meister ist.

=== Namen

Zwerg: Durga, Aelfar, Gerda, Rurgosh, Bjorn, Drummond, Helga, siggrun, Freya
Mensch: Wesley, Brinton, Jon, Sara; Hawthron, Elise, Clarke, Lenore, Piotr, Dahlia, Carmine

=== Aussehen

Wähle von Jeden eins:
Freundlichen Augen, scharfe Augen oder Traurige Augen
Tonsur, wildes Haar oder Glatze
Wallenden Gewändern, Mönchsgewand, oder Gewöhnliches Gewand 

Dünnen Körper, Knorriger Körper oder Schwabeliger Körper 

=== Attribute

Deine maximalen TP sind 8+ KON
Grundschaden ist W6

=== Anfangs Züge

Wähle eine Rasse um die Zugehörigen Züge zu erhalten.

==== Zwerg
Du bist eins mit den Stein.
Wenn du dich Unterhältst, dann lernst du eine spezielle Art der Wörter des Ungesprochenen, welche nur die Steine kennen.

==== Mensch

Dein Glaube ist vielfältig.
Wähle einen Magier Zauber. Dieser Zauber gilt als wäre er ein Kleriker Zauber.
Du beginnst mit folgenden Zügen:

==== Gottheit

Du dienst und verehrst eine Gottheit oder Kraft, die dir deine Zauber Gewährt.
Gebe deinen Gott einen Namen (vielleicht Helferth, Sucellus, Zorica oder Krugon der Trostlose) und wähle Seinen/Ihren Einflussbereich.
. Heilung und Wiederherstellung
Blutiger Eroberer 
Zivilisation
Wissen und Verborgenes
Die Unterdrückten und Vergessenen
Schatten der Wahrheit
Wähle eine Lehre deiner Religion:
     Ihre Religion predigt die Heiligkeit des Leidens, erhalte das Gebet: Leiden
     Ihre Religion ist Okkult und Abgeschottet, erhalte das Gebet: gewinnen von Geheimnissen
     Ihre Religion hat wichtige Opferriten, erhalte das Gebet: Offenbarung 
     Ihre Religion glaubt an den Gerichtskampf, erhalte das Gebet: Persönlicher Sieg

==== Göttliche Führung

Wenn du nach den Geboten deines Glaubens, zu deiner Gottheit bettest, wird dir nützliches Wissen gewährt oder ein Segen der mit den Einflussbereich deiner Gottheit verwandt ist.
Der SL wird dir weiteres sagen.

==== Untote

Wenn du dein Heiliges Symbol hochhält  und deine Gottheit um Schutz anrufst, Würfle WEIS
 7+, solange du weiter bettest und dein heiliges Symbol schwingst, wird kein Untoter in deine Nähe kommen.
10+, zusätzlich betäubst du Intelligente Untote und veranlasst Hirnlose Untote zum Fliehen. 
Aggression unterbricht die Effekte und die Untoten können Normal agieren.
Intelligente Untote können immer noch Wege finden dich aus der Ferne anzugreifen.
Sie sind schlau genug dazu.

