== Das Spiel spielen

_Dungeon World_ zu spielen heißt, sich zu unterhalten; jemand sagt etwas, du antwortest, vielleicht schaltet sich noch jemand ein.
Wir unterhalten uns über die Fiktion – die Welt eurer Charaktere und die Dinge, die um sie herum geschehen.
Im Laufe des Spiels werden sich auch die Regeln einschalten.
Sie haben ebenfalls etwas über die Welt zu sagen.
In _Dungeon World_ gibt es keine Runden oder Initiative, keine Regeln, die festlegen, wer wann an der Reihe ist.
Stattdessen nehmen die Spieler einfach teil an der Unterhaltung, die von Natur aus ein gewisses Hin und Her beinhaltet.
Der SL sagt etwas, auf das die Spieler eingehen.
Die Spieler stellen Fragen oder beschreiben, was sie tun, und der SL erzählt, was daraufhin passiert.
_Dungeon World_ ist niemals ein Monolog, immer eine Unterhaltung.

Die Regeln helfen, die Unterhaltung im Sinne des Spiels auszugestalten.
Wenn der SL und die Spieler sich unterhalten, reden die Regeln und die Fiktion mit.
Jede Regel hat einen ausdrücklich beschriebenen, fiktionalen Auslöser, über den sie dir mitteilt, wenn sie zur Anwendung kommt.

Wie in jedem guten Gespräch ist die Zeit, in der du zuhörst, genauso wichtig wie die, die du mit Reden verbringst – denn die Details, die von den anderen Leuten am Tisch etabliert wurden, sind entscheidend für dich.
Sie können maßgebend dafür sein, welche Züge du machen kannst, dir neue Möglichkeiten eröffnen, oder dich vor eine Herausforderung stellen, der du ins Auge blicken musst.
Die Unterhaltung funktioniert am besten, wenn wir alle zuhören, Fragen stellen und auf den Beiträgen der anderen aufbauen.

Dieses Kapitel dreht sich darum, wie _Dungeon World_ gespielt wird.
Du findest hier Informationen über die Regeln, wie sie sich aus dem Spiel ergeben und wiederum dazu beitragen.
Wir werden sowohl die allgemeinen Regeln behandeln (zum Beispiel, wie man Züge macht) als auch speziellere, die nur in bestimmten Situationen zur Anwendung kommen (wie man mit Schaden und Trefferpunkten umgeht).

=== Attribute und Modifikatoren

Viele der in diesem Kapitel besprochenen Regeln erwähnen die _Attribute_ eines Charakters und ihre _Modifikatoren_.
Die Attribute sind _Stärke_, _Konstitution_, _Geschicklichkeit_, _Intelligenz_, _Weisheit_ und _Charisma_.
Sie beschreiben ganz allgemein die Befähigung eines Charakters auf ihrem Gebiet, auf einer Skala von 3 bis 18, wobei 18 das absolute Höchstmaß dessen darstellt, was ein Sterblicher auf diesem Gebiet leisten kann.

Jedes Attribut hat außerdem einen _Modifikator_, der benutzt wird, wenn gegen dieses Attribut gewürfelt wird.
Sie werden als _STR_, _KON_, _GES_, _INT_, _WEI_ und _CHA_ abgekürzt.
Modifikatoren reichen von -3 bis +3.
Ein Modifikator wird immer von dem Attributwert abgeleitet, den du im Moment innehast.

=== Züge machen

Die fundamentale Regeleinheit in _Dungeon World_ ist der _Zug_.
Ein Zug sieht so aus:

'''
*Wenn du einen Gegner im Nahkampf angreifst,* würfle+STÄ.
✴ Bei einer 10+ fügst du ihm Schaden zu und entrinnst seinem Angriff.
Wenn du willst, kannst du außerdem +1W6 Schaden machen, setzt dich dabei aber dem Angriff deines Gegners aus.
✴ Bei einer 7–9 fügst du deinem Gegner Schaden zu und er kann einen Angriff gegen dich ausführen.

'''

Züge sind Regeln, die dir sagen, wenn sie ausgelöst werden und welche Auswirkungen sie haben.
Ein Zug hängt von einer fiktionalen Handlung ab und hat immer einen fiktionalen Effekt.
"Fiktional" bedeutet hier, dass sowohl die auslösende Handlung als auch der Effekt aus der Welt der Charaktere stammen, die wir beschreiben.
Der obige Zug wird ausgelöst, "wenn du einen Gegner im Nahkampf angreifst".
Der Effekt ist das, was dein Angriff zur Folge hat:
Einen Würfelwurf und unterschiedliche Situationen, die sich aus diesem Wurf ergeben können, je nachdem, wie die Würfel gefallen sind.

Wenn ein Spieler beschreibt, was sein Charakter tut und damit einen Zug auslöst, dann geschieht dieser Zug und seine Regeln kommen zur Anwendung.
Wenn der Zug einen Würfelwurf erfordert, wird dir seine Beschreibung erklären, was du würfeln musst und was das Ergebnis bedeutet.

Ein Charakter kann die fiktionale Handlung, die Auslöser für einen Zug ist, nicht unternehmen, ohne diesen Zug auszulösen.
Wenn Isaac dem SL sagt, dass sein Charakter an einem durchgedrehten, axtschwingenden Ork vorbeischlüpft und durch die offene Tür flieht, dann macht er den _Gefahr trotzen_-Zug – denn dessen Auslöser ist "wenn du trotz einer unmittelbaren Gefahr handelst".
Isaac kann nicht einfach beschreiben, wie sein Charakter an dem Ork vorbeiläuft, ohne den _Gefahr trotzen_-Zug zu machen.
Genauso kann den _Gefahr trotzen_-Zug nicht machen, wenn er nicht "trotz einer unmittelbaren Gefahr handelt" oder "ein drohendes Unheil hinnehmen muss".
Der Zug und die Fiktion gehen Hand in Hand.

Jeder am Tisch sollte darauf achten, ob Züge ausgelöst werden.
Wenn es jemals unklar sein sollte, ob ein Zug ausgelöst wird oder nicht, solltet ihr zusammenarbeiten und Klarheit darüber schaffen, was gerade passiert.
Fragt jeden Beteiligten, bis ihr alle auf der gleichen Wellenlänge seid und die Situation mit gleichen Augen seht.
Dann würfelt – oder auch nicht, je nachdem, was die Situation erfordert.

==== Züge und Würfel

Die meisten Züge beinhalten den Ausdruck "würfle+X", wobei _X_ einer der Attributmodifikatoren deines Charakters ist.
Solange der Zug nichts anderes vorgibt, bedeutet "würfle" immer, dass du zwei sechsseitige Würfel wirfst, das Ergebnis zusammenzählst und den Wert des angegebenen Modifikators addierst.
Bei manchen Zügen addierst du keinen Modifikator, sondern einen anderen Wert:

____
Ich mache einen Zug, bei dem ich +STR würfeln muss.
Mein STR-Modifikator ist +1.
Ich würfle zwei sechsseitige Würfel und bekomme eine Eins und eine Vier.
Das Endergebnis ist sechs.
____

Die Ergebnisse fallen immer unter eine von drei grundlegenden Kategorien.
Eine Augenzahl von 10 oder größer (geschrieben als 10+) ist das beste Resultat.
Eine Zahl zwischen 7 und 9 ist immer noch ein Erfolg, kommt allerdings mit Komplikationen oder kostet dich etwas.
Eine 6 oder niedriger bedeutet Ärger, aber du darfst dir dafür auch einen Erfahrungspunkt gutschreiben.

Schadenswürfe funktionieren ein wenig anders.
Sie benutzen unterschiedliche Würfel, je nachdem, wer oder was den Schaden anrichtet.

==== Züge und Ausrüstung

Die wichtigste Rolle, die der Ausrüstung deines Charakters zukommt, ist die Unterstützung bei der Beschreibung der Züge, die er macht.
Ein Charakter ohne Waffe wird im Kampf gegen einen Drachen kein _Hauen und Stechen_ auslösen, da ein beherzter Faustschlag herzlich wenig gegen zentimeterdicke Schuppen ausrichtet.
Der Angriff zählt daher nicht als Auslöser für den Zug.

Deine Ausrüstung kann das Auslösen eines Zuges aber auch verhindern.
Das Erklimmen eines vereisten Felsvorsprungs bedeutet normalerweise _Gefahr trotzen_, aber ein Satz anständiger Kletterausrüstung könnte es dir erlauben, die "unmittelbare Gefahr" zu reduzieren oder das "drohende Unheil" abzuwenden, so dass du den Zug nicht auslöst.

Von allen Gegenständen haben Waffen am häufigsten Einfluss darauf, welche Züge du auslösen kannst.
Ein Charakter mit einem Dolch kann problemlos versuchen, den Goblin zu erstechen, der sich in sein Bein verbissen hat, und dabei _Hauen und Stechen_ auslösen.
Jemand mit einer Hellebarde wird hingegen große Probleme haben, diese gegen einen so nahen Feind in Stellung zu bringen.

Gegenstände und Ausrüstung jeder Art können mit _Marken_ versehen sein.
Marken sind Schlagworte, die benutzt werden, um Dinge zu beschreiben.
Manche verändern bestimmte Regeln (z.B. verminderter Schaden auf Rüstung, magische Boni/Mali auf einen Zug oder ein Attribut in bestimmten Situationen)
Andere Marken haben Auswirkungen auf die Fiktion (wie die _[nah]_-Marke, die angibt, wie weit ein Gegner entfernt sein muss, damit du ihn mit dieser Waffe angreifen kannst).
Marken helfen dir, die Handlungen deines Charakters zu beschreiben, wenn er einen Gegenstand nutzt.
Sie geben dem SL außerdem Informationen darüber, was bei der Benutzung eines Gegenstands schiefgehen kann, oder was für Konsequenzen ein fehlgeschlagener Wurf haben könnte.

==== Züge und ihre Auswirkungen

Die Folgen eines Zuges kommen immer in der ausgedachten Welt zum Tragen, in der die Charaktere leben.
Eine 10+ auf _Hauen und Stechen_ bewirkt nicht nur den mechanischen Effekt, sie heißt, dass du jemanden erfolgreich angegriffen und ihm Leid zugefügt hast.

Sobald ihr euch über die Auswirkungen eines Zuges im Klaren seid, lasst sie im Rahmen eurer Geschichte zum Tragen kommen und wendet euch wieder eurer Unterhaltung zu.
Nach einem Zug kommt ihr immer wieder auf das zurück, was im Spiel geschieht.

Manche Züge haben unmittelbare mechanische Auswirkungen, wie das Verursachen von Schaden oder die Verleihung eines Bonus auf den nächsten Wurf.
Diese Effekte spiegeln sich immer auch in der Welt der Charaktere wider;
stell sicher, dass du sie in deine Beschreibung der Auswirkungen mit einbeziehst.

===== Manche Züge…

…sagen "mach deinen Schaden" oder "richte deinen Schaden an".
"Schaden anrichten" heißt, dass du den Schadenswürfel deiner Klasse wirfst.
Manchmal kann deine Waffe dir auch einen Bonus oder Malus auf den Schaden gewähren.
Du benutzt deinen Schadenswürfel immer dann, wenn du einen Angriff durchführst, der deinem Ziel auch tatsächlich Schaden zufügen kann.
Des bedeutet normalerweise, dass du eine Waffe führen musst – aber unter den richtigen Bedingungen oder mit dem richtigen Training können auch deine Fäuste zu Waffen werden.

…sagen "nimm +1 voraus".
Das bedeutet, dass du einen Bonus von +1 auf deinen nächsten Wurf für einen Zug bekommst (nicht auf einen Schadenswurf).
Der Bonus kann größer ausfallen als +1, oder es kann sogar ein Malus wie -1 sein.
Es kann auch eine Bedingung eingeschlossen sein, wie "Nimm +1 voraus auf _Hauen und Stechen_"; in diesem Fall bekommst du den Bonus nur auf deinen nächsten _Hauen und Stechen_-Wurf, nicht auf andere Züge.

…sagen "nimm +1 fortlaufend".
Das bedeutet, dass du +1 auf alle folgenden Würfe auf Züge erhältst (nicht auf Schadenswürfe).
Der Bonus kann auch hier größer ausfallen als +1, oder es kann ein Malus wie -1 sein.
Es kann auch eine Bedingung eingeschlossen sein, wie "Nimm +1 voraus auf _Salve_".
Wenn du einen fortlaufenden Bonus bekommst, werden dir auch die Bedingungen genannt, unter denen du den Bonus verlierst, z.B. "bis du den Zauber auflöst" oder "bis du vor deinem Gott Buße getan hast".

…geben dir "Reserve".
Reserve ist eine Art Währung, die dir erlaubt, die Auswirkungen eines Zuges später zur Auswirkung zu bringen.
Dazu musst du sie so ausgeben, wie der Zug es beschreibt.
Reserve ist immer spezifisch für den Zug, der sie erzeugt hat - du kannst Reserve von _Verteidigen_ zum Beispiel nicht für _Fallenkunde_ ausgeben, oder andersrum.

…stellen dich vor die Wahl.
Deine Entscheidung wirkt sich – wie bei allen Zügen – sowohl auf die Fiktion als auch auf die spielmechanischen Folgen aus.
Deine Entscheidung, bei einer 10+ auf deinem _Hauen und Stechen_-Wurf mehr Schaden anzurichten und dich im Gegenzug dem Angriff deines Gegners auszusetzen, ist genau das, was deinem Charakter passiert:
Sein Vorteil im Gefecht ist groß genug, dass er nach seinem Angriff entweder sicher zurückweichen oder sein Glück herausfordern kann.

…geben dir die Gelegenheit, etwas über deinen Charakter und seine Geschichte zu sagen.
Wenn du _Weisheit kundtust_, kann der SL dich fragen, woher du die Informationen hast, die er in deinem Namen preisgibt.
Nutze diese Gelegenheit, zur Ausgestaltung eurer Welt beizutragen, und zeig ihnen, wer dein Charakter wirklich ist.
Du solltest dabei nur die schon etablierten Fakten im Hinterkopf behalten und versuchen, im Einklang mit der bis hierhin beschriebenen Geschichte zu bleiben.

…sagen "schreibe dir EP gut".
Das bedeutest, dass du einen Punkt zu deiner Gesamterfahrung hinzufügen darfst.
